# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/edp11.ui'
#
# Created: Wed Aug 15 02:45:13 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(908, 610)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(False)
        self.tabWidget.setGeometry(QtCore.QRect(10, 28, 888, 530))
        self.tabWidget.setStyleSheet(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_DatosPers = QtGui.QWidget()
        self.tab_DatosPers.setObjectName(_fromUtf8("tab_DatosPers"))
        self.pushButton_InfMed = QtGui.QPushButton(self.tab_DatosPers)
        self.pushButton_InfMed.setGeometry(QtCore.QRect(40, 300, 141, 27))
        self.pushButton_InfMed.setObjectName(_fromUtf8("pushButton_InfMed"))
        self.label_nom = QtGui.QLabel(self.tab_DatosPers)
        self.label_nom.setGeometry(QtCore.QRect(40, 68, 62, 17))
        self.label_nom.setObjectName(_fromUtf8("label_nom"))
        self.lineEdit_Nom = QtGui.QLineEdit(self.tab_DatosPers)
        self.lineEdit_Nom.setGeometry(QtCore.QRect(170, 64, 136, 27))
        self.lineEdit_Nom.setText(_fromUtf8(""))
        self.lineEdit_Nom.setObjectName(_fromUtf8("lineEdit_Nom"))
        self.label_apell = QtGui.QLabel(self.tab_DatosPers)
        self.label_apell.setGeometry(QtCore.QRect(373, 68, 71, 17))
        self.label_apell.setObjectName(_fromUtf8("label_apell"))
        self.lineEdit_Apell = QtGui.QLineEdit(self.tab_DatosPers)
        self.lineEdit_Apell.setGeometry(QtCore.QRect(453, 64, 211, 27))
        self.lineEdit_Apell.setObjectName(_fromUtf8("lineEdit_Apell"))
        self.label_edad = QtGui.QLabel(self.tab_DatosPers)
        self.label_edad.setGeometry(QtCore.QRect(373, 110, 41, 17))
        self.label_edad.setObjectName(_fromUtf8("label_edad"))
        self.lineEdit_Edad = QtGui.QLineEdit(self.tab_DatosPers)
        self.lineEdit_Edad.setEnabled(False)
        self.lineEdit_Edad.setGeometry(QtCore.QRect(453, 105, 34, 27))
        self.lineEdit_Edad.setReadOnly(True)
        self.lineEdit_Edad.setObjectName(_fromUtf8("lineEdit_Edad"))
        self.label_sexo = QtGui.QLabel(self.tab_DatosPers)
        self.label_sexo.setGeometry(QtCore.QRect(40, 32, 41, 17))
        self.label_sexo.setObjectName(_fromUtf8("label_sexo"))
        self.combo_FM = QtGui.QComboBox(self.tab_DatosPers)
        self.combo_FM.setEnabled(False)
        self.combo_FM.setGeometry(QtCore.QRect(170, 31, 51, 21))
        self.combo_FM.setEditable(False)
        self.combo_FM.setObjectName(_fromUtf8("combo_FM"))
        self.combo_FM.addItem(_fromUtf8(""))
        self.combo_FM.addItem(_fromUtf8(""))
        self.date_FNac = QtGui.QDateTimeEdit(self.tab_DatosPers)
        self.date_FNac.setGeometry(QtCore.QRect(170, 105, 115, 27))
        self.date_FNac.setDate(QtCore.QDate(1950, 1, 1))
        self.date_FNac.setCalendarPopup(True)
        self.date_FNac.setObjectName(_fromUtf8("date_FNac"))
        self.label_FNac = QtGui.QLabel(self.tab_DatosPers)
        self.label_FNac.setGeometry(QtCore.QRect(40, 110, 118, 16))
        self.label_FNac.setObjectName(_fromUtf8("label_FNac"))
        self.label_dni = QtGui.QLabel(self.tab_DatosPers)
        self.label_dni.setGeometry(QtCore.QRect(40, 150, 47, 17))
        self.label_dni.setObjectName(_fromUtf8("label_dni"))
        self.lineEdit_Dni = QtGui.QLineEdit(self.tab_DatosPers)
        self.lineEdit_Dni.setGeometry(QtCore.QRect(170, 145, 101, 27))
        self.lineEdit_Dni.setObjectName(_fromUtf8("lineEdit_Dni"))
        self.label_dir = QtGui.QLabel(self.tab_DatosPers)
        self.label_dir.setGeometry(QtCore.QRect(373, 150, 71, 17))
        self.label_dir.setObjectName(_fromUtf8("label_dir"))
        self.lineEdit_Dir = QtGui.QLineEdit(self.tab_DatosPers)
        self.lineEdit_Dir.setGeometry(QtCore.QRect(453, 145, 380, 27))
        self.lineEdit_Dir.setReadOnly(False)
        self.lineEdit_Dir.setObjectName(_fromUtf8("lineEdit_Dir"))
        self.label_prof = QtGui.QLabel(self.tab_DatosPers)
        self.label_prof.setGeometry(QtCore.QRect(373, 190, 71, 17))
        self.label_prof.setObjectName(_fromUtf8("label_prof"))
        self.lineEdit_Prof = QtGui.QLineEdit(self.tab_DatosPers)
        self.lineEdit_Prof.setGeometry(QtCore.QRect(453, 185, 380, 27))
        self.lineEdit_Prof.setObjectName(_fromUtf8("lineEdit_Prof"))
        self.label_tlf = QtGui.QLabel(self.tab_DatosPers)
        self.label_tlf.setGeometry(QtCore.QRect(40, 190, 71, 17))
        self.label_tlf.setObjectName(_fromUtf8("label_tlf"))
        self.lineEdit_Tlf = QtGui.QLineEdit(self.tab_DatosPers)
        self.lineEdit_Tlf.setGeometry(QtCore.QRect(170, 185, 113, 27))
        self.lineEdit_Tlf.setObjectName(_fromUtf8("lineEdit_Tlf"))
        self.label_7 = QtGui.QLabel(self.tab_DatosPers)
        self.label_7.setGeometry(QtCore.QRect(500, 112, 35, 14))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tabWidget.addTab(self.tab_DatosPers, _fromUtf8(""))
        self.tab_EstAntr = QtGui.QWidget()
        self.tab_EstAntr.setObjectName(_fromUtf8("tab_EstAntr"))
        self.group_Antr = QtGui.QGroupBox(self.tab_EstAntr)
        self.group_Antr.setGeometry(QtCore.QRect(10, 0, 412, 341))
        self.group_Antr.setStyleSheet(_fromUtf8(""))
        self.group_Antr.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.group_Antr.setFlat(True)
        self.group_Antr.setCheckable(False)
        self.group_Antr.setObjectName(_fromUtf8("group_Antr"))
        self.label_peso = QtGui.QLabel(self.group_Antr)
        self.label_peso.setGeometry(QtCore.QRect(24, 49, 40, 17))
        self.label_peso.setObjectName(_fromUtf8("label_peso"))
        self.label_peso_kg = QtGui.QLabel(self.group_Antr)
        self.label_peso_kg.setGeometry(QtCore.QRect(150, 49, 21, 17))
        self.label_peso_kg.setObjectName(_fromUtf8("label_peso_kg"))
        self.label_altura = QtGui.QLabel(self.group_Antr)
        self.label_altura.setGeometry(QtCore.QRect(24, 79, 47, 17))
        self.label_altura.setObjectName(_fromUtf8("label_altura"))
        self.label_alt_cm = QtGui.QLabel(self.group_Antr)
        self.label_alt_cm.setGeometry(QtCore.QRect(150, 80, 22, 17))
        self.label_alt_cm.setObjectName(_fromUtf8("label_alt_cm"))
        self.label_imc = QtGui.QLabel(self.group_Antr)
        self.label_imc.setGeometry(QtCore.QRect(224, 49, 50, 20))
        self.label_imc.setObjectName(_fromUtf8("label_imc"))
        self.label_pob = QtGui.QLabel(self.group_Antr)
        self.label_pob.setGeometry(QtCore.QRect(224, 79, 62, 17))
        self.label_pob.setObjectName(_fromUtf8("label_pob"))
        self.label_porc = QtGui.QLabel(self.group_Antr)
        self.label_porc.setGeometry(QtCore.QRect(360, 49, 16, 17))
        self.label_porc.setObjectName(_fromUtf8("label_porc"))
        self.label_pob_kg = QtGui.QLabel(self.group_Antr)
        self.label_pob_kg.setGeometry(QtCore.QRect(360, 79, 21, 17))
        self.label_pob_kg.setObjectName(_fromUtf8("label_pob_kg"))
        self.doubleSpin_Peso = QtGui.QDoubleSpinBox(self.group_Antr)
        self.doubleSpin_Peso.setGeometry(QtCore.QRect(78, 44, 64, 27))
        self.doubleSpin_Peso.setMaximum(999.99)
        self.doubleSpin_Peso.setSingleStep(0.01)
        self.doubleSpin_Peso.setObjectName(_fromUtf8("doubleSpin_Peso"))
        self.doubleSpin_Alt = QtGui.QDoubleSpinBox(self.group_Antr)
        self.doubleSpin_Alt.setGeometry(QtCore.QRect(78, 74, 64, 27))
        self.doubleSpin_Alt.setDecimals(0)
        self.doubleSpin_Alt.setMaximum(999.0)
        self.doubleSpin_Alt.setObjectName(_fromUtf8("doubleSpin_Alt"))
        self.doubleSpin_IMC = QtGui.QDoubleSpinBox(self.group_Antr)
        self.doubleSpin_IMC.setGeometry(QtCore.QRect(289, 44, 64, 27))
        self.doubleSpin_IMC.setStyleSheet(_fromUtf8("background-color:"))
        self.doubleSpin_IMC.setReadOnly(True)
        self.doubleSpin_IMC.setMaximum(999.99)
        self.doubleSpin_IMC.setSingleStep(0.01)
        self.doubleSpin_IMC.setObjectName(_fromUtf8("doubleSpin_IMC"))
        self.doubleSpin_POb = QtGui.QDoubleSpinBox(self.group_Antr)
        self.doubleSpin_POb.setGeometry(QtCore.QRect(289, 74, 64, 27))
        self.doubleSpin_POb.setMaximum(999.99)
        self.doubleSpin_POb.setSingleStep(0.01)
        self.doubleSpin_POb.setObjectName(_fromUtf8("doubleSpin_POb"))
        self.label_complex = QtGui.QLabel(self.group_Antr)
        self.label_complex.setGeometry(QtCore.QRect(24, 179, 91, 17))
        self.label_complex.setObjectName(_fromUtf8("label_complex"))
        self.combo_Complex = QtGui.QComboBox(self.group_Antr)
        self.combo_Complex.setGeometry(QtCore.QRect(160, 175, 89, 27))
        self.combo_Complex.setObjectName(_fromUtf8("combo_Complex"))
        self.combo_Complex.addItem(_fromUtf8(""))
        self.combo_Complex.addItem(_fromUtf8(""))
        self.combo_Complex.addItem(_fromUtf8(""))
        self.label_cint = QtGui.QLabel(self.group_Antr)
        self.label_cint.setGeometry(QtCore.QRect(224, 110, 54, 17))
        self.label_cint.setObjectName(_fromUtf8("label_cint"))
        self.doubleSpin_Cad = QtGui.QDoubleSpinBox(self.group_Antr)
        self.doubleSpin_Cad.setGeometry(QtCore.QRect(78, 104, 64, 27))
        self.doubleSpin_Cad.setMaximum(999.99)
        self.doubleSpin_Cad.setSingleStep(0.01)
        self.doubleSpin_Cad.setObjectName(_fromUtf8("doubleSpin_Cad"))
        self.label_cader = QtGui.QLabel(self.group_Antr)
        self.label_cader.setGeometry(QtCore.QRect(24, 110, 53, 17))
        self.label_cader.setObjectName(_fromUtf8("label_cader"))
        self.doubleSpin_Cint = QtGui.QDoubleSpinBox(self.group_Antr)
        self.doubleSpin_Cint.setGeometry(QtCore.QRect(289, 104, 64, 27))
        self.doubleSpin_Cint.setMaximum(999.99)
        self.doubleSpin_Cint.setSingleStep(0.01)
        self.doubleSpin_Cint.setObjectName(_fromUtf8("doubleSpin_Cint"))
        self.label_tricip = QtGui.QLabel(self.group_Antr)
        self.label_tricip.setGeometry(QtCore.QRect(24, 144, 118, 17))
        self.label_tricip.setObjectName(_fromUtf8("label_tricip"))
        self.label_cad_cm = QtGui.QLabel(self.group_Antr)
        self.label_cad_cm.setGeometry(QtCore.QRect(150, 110, 22, 17))
        self.label_cad_cm.setObjectName(_fromUtf8("label_cad_cm"))
        self.label_cint_cm = QtGui.QLabel(self.group_Antr)
        self.label_cint_cm.setGeometry(QtCore.QRect(360, 110, 22, 17))
        self.label_cint_cm.setObjectName(_fromUtf8("label_cint_cm"))
        self.doubleSpin_Tricip = QtGui.QDoubleSpinBox(self.group_Antr)
        self.doubleSpin_Tricip.setGeometry(QtCore.QRect(160, 140, 64, 27))
        self.doubleSpin_Tricip.setMaximum(999.99)
        self.doubleSpin_Tricip.setSingleStep(0.01)
        self.doubleSpin_Tricip.setObjectName(_fromUtf8("doubleSpin_Tricip"))
        self.label_pideal = QtGui.QLabel(self.group_Antr)
        self.label_pideal.setGeometry(QtCore.QRect(24, 216, 71, 17))
        self.label_pideal.setObjectName(_fromUtf8("label_pideal"))
        self.lineEdit_PIdeal = QtGui.QLineEdit(self.group_Antr)
        self.lineEdit_PIdeal.setGeometry(QtCore.QRect(160, 210, 89, 27))
        self.lineEdit_PIdeal.setReadOnly(True)
        self.lineEdit_PIdeal.setObjectName(_fromUtf8("lineEdit_PIdeal"))
        self.label_tr_cm = QtGui.QLabel(self.group_Antr)
        self.label_tr_cm.setGeometry(QtCore.QRect(232, 144, 23, 17))
        self.label_tr_cm.setObjectName(_fromUtf8("label_tr_cm"))
        self.label_pesoi_kg = QtGui.QLabel(self.group_Antr)
        self.label_pesoi_kg.setGeometry(QtCore.QRect(255, 216, 21, 17))
        self.label_pesoi_kg.setObjectName(_fromUtf8("label_pesoi_kg"))
        self.toolButton_Grado = QtGui.QToolButton(self.group_Antr)
        self.toolButton_Grado.setGeometry(QtCore.QRect(384, 48, 25, 20))
        self.toolButton_Grado.setStyleSheet(_fromUtf8("_"))
        self.toolButton_Grado.setText(_fromUtf8(""))
        self.toolButton_Grado.setObjectName(_fromUtf8("toolButton_Grado"))
        self.label_PMG = QtGui.QLabel(self.group_Antr)
        self.label_PMG.setGeometry(QtCore.QRect(24, 280, 158, 17))
        self.label_PMG.setObjectName(_fromUtf8("label_PMG"))
        self.label_PL = QtGui.QLabel(self.group_Antr)
        self.label_PL.setGeometry(QtCore.QRect(24, 310, 122, 17))
        self.label_PL.setObjectName(_fromUtf8("label_PL"))
        self.doubleSpin_PMG = QtGui.QDoubleSpinBox(self.group_Antr)
        self.doubleSpin_PMG.setGeometry(QtCore.QRect(229, 275, 64, 27))
        self.doubleSpin_PMG.setReadOnly(False)
        self.doubleSpin_PMG.setMaximum(999.99)
        self.doubleSpin_PMG.setSingleStep(0.01)
        self.doubleSpin_PMG.setObjectName(_fromUtf8("doubleSpin_PMG"))
        self.label_porc_2 = QtGui.QLabel(self.group_Antr)
        self.label_porc_2.setGeometry(QtCore.QRect(300, 280, 16, 17))
        self.label_porc_2.setObjectName(_fromUtf8("label_porc_2"))
        self.doubleSpin_PL = QtGui.QDoubleSpinBox(self.group_Antr)
        self.doubleSpin_PL.setGeometry(QtCore.QRect(229, 305, 64, 27))
        self.doubleSpin_PL.setReadOnly(False)
        self.doubleSpin_PL.setMaximum(999.99)
        self.doubleSpin_PL.setSingleStep(0.01)
        self.doubleSpin_PL.setObjectName(_fromUtf8("doubleSpin_PL"))
        self.label_porc_3 = QtGui.QLabel(self.group_Antr)
        self.label_porc_3.setGeometry(QtCore.QRect(300, 310, 16, 17))
        self.label_porc_3.setObjectName(_fromUtf8("label_porc_3"))
        self.label_PPac = QtGui.QLabel(self.group_Antr)
        self.label_PPac.setGeometry(QtCore.QRect(24, 248, 96, 17))
        self.label_PPac.setObjectName(_fromUtf8("label_PPac"))
        self.label_ppac_kg = QtGui.QLabel(self.group_Antr)
        self.label_ppac_kg.setGeometry(QtCore.QRect(231, 247, 21, 17))
        self.label_ppac_kg.setObjectName(_fromUtf8("label_ppac_kg"))
        self.doubleSpin_PPac = QtGui.QDoubleSpinBox(self.group_Antr)
        self.doubleSpin_PPac.setGeometry(QtCore.QRect(160, 242, 64, 27))
        self.doubleSpin_PPac.setMaximum(999.99)
        self.doubleSpin_PPac.setSingleStep(0.01)
        self.doubleSpin_PPac.setObjectName(_fromUtf8("doubleSpin_PPac"))
        self.line_vert = QtGui.QFrame(self.tab_EstAntr)
        self.line_vert.setGeometry(QtCore.QRect(440, 0, 5, 347))
        self.line_vert.setFrameShape(QtGui.QFrame.VLine)
        self.line_vert.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_vert.setObjectName(_fromUtf8("line_vert"))
        self.group_NecEnerg = QtGui.QGroupBox(self.tab_EstAntr)
        self.group_NecEnerg.setGeometry(QtCore.QRect(459, 0, 411, 341))
        self.group_NecEnerg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.group_NecEnerg.setObjectName(_fromUtf8("group_NecEnerg"))
        self.label_mb = QtGui.QLabel(self.group_NecEnerg)
        self.label_mb.setGeometry(QtCore.QRect(30, 50, 131, 17))
        self.label_mb.setObjectName(_fromUtf8("label_mb"))
        self.label_activ = QtGui.QLabel(self.group_NecEnerg)
        self.label_activ.setGeometry(QtCore.QRect(30, 90, 69, 17))
        self.label_activ.setObjectName(_fromUtf8("label_activ"))
        self.combo_Activ = QtGui.QComboBox(self.group_NecEnerg)
        self.combo_Activ.setGeometry(QtCore.QRect(223, 82, 101, 31))
        self.combo_Activ.setObjectName(_fromUtf8("combo_Activ"))
        self.combo_Activ.addItem(_fromUtf8(""))
        self.combo_Activ.addItem(_fromUtf8(""))
        self.combo_Activ.addItem(_fromUtf8(""))
        self.label_increm = QtGui.QLabel(self.group_NecEnerg)
        self.label_increm.setGeometry(QtCore.QRect(30, 130, 171, 17))
        self.label_increm.setObjectName(_fromUtf8("label_increm"))
        self.label_reduc = QtGui.QLabel(self.group_NecEnerg)
        self.label_reduc.setGeometry(QtCore.QRect(30, 170, 151, 17))
        self.label_reduc.setObjectName(_fromUtf8("label_reduc"))
        self.doubleSpin_MB = QtGui.QDoubleSpinBox(self.group_NecEnerg)
        self.doubleSpin_MB.setGeometry(QtCore.QRect(223, 45, 81, 27))
        self.doubleSpin_MB.setReadOnly(True)
        self.doubleSpin_MB.setMaximum(9999.99)
        self.doubleSpin_MB.setSingleStep(0.01)
        self.doubleSpin_MB.setObjectName(_fromUtf8("doubleSpin_MB"))
        self.doubleSpin_Increm = QtGui.QDoubleSpinBox(self.group_NecEnerg)
        self.doubleSpin_Increm.setGeometry(QtCore.QRect(223, 125, 81, 27))
        self.doubleSpin_Increm.setReadOnly(True)
        self.doubleSpin_Increm.setMaximum(9999.99)
        self.doubleSpin_Increm.setSingleStep(0.01)
        self.doubleSpin_Increm.setObjectName(_fromUtf8("doubleSpin_Increm"))
        self.doubleSpin_Reduc = QtGui.QDoubleSpinBox(self.group_NecEnerg)
        self.doubleSpin_Reduc.setGeometry(QtCore.QRect(223, 166, 81, 27))
        self.doubleSpin_Reduc.setReadOnly(True)
        self.doubleSpin_Reduc.setMaximum(9999.99)
        self.doubleSpin_Reduc.setSingleStep(0.01)
        self.doubleSpin_Reduc.setObjectName(_fromUtf8("doubleSpin_Reduc"))
        self.label_et = QtGui.QLabel(self.group_NecEnerg)
        self.label_et.setGeometry(QtCore.QRect(30, 210, 91, 17))
        self.label_et.setObjectName(_fromUtf8("label_et"))
        self.doubleSpin_ET = QtGui.QDoubleSpinBox(self.group_NecEnerg)
        self.doubleSpin_ET.setGeometry(QtCore.QRect(223, 206, 81, 27))
        self.doubleSpin_ET.setReadOnly(True)
        self.doubleSpin_ET.setMaximum(9999.99)
        self.doubleSpin_ET.setSingleStep(0.01)
        self.doubleSpin_ET.setObjectName(_fromUtf8("doubleSpin_ET"))
        self.label_mb_kc = QtGui.QLabel(self.group_NecEnerg)
        self.label_mb_kc.setGeometry(QtCore.QRect(315, 50, 35, 17))
        self.label_mb_kc.setObjectName(_fromUtf8("label_mb_kc"))
        self.label_incr_kc = QtGui.QLabel(self.group_NecEnerg)
        self.label_incr_kc.setGeometry(QtCore.QRect(315, 130, 35, 17))
        self.label_incr_kc.setObjectName(_fromUtf8("label_incr_kc"))
        self.label_reduc_kc = QtGui.QLabel(self.group_NecEnerg)
        self.label_reduc_kc.setGeometry(QtCore.QRect(315, 170, 35, 17))
        self.label_reduc_kc.setObjectName(_fromUtf8("label_reduc_kc"))
        self.label_et_kc = QtGui.QLabel(self.group_NecEnerg)
        self.label_et_kc.setGeometry(QtCore.QRect(315, 210, 35, 17))
        self.label_et_kc.setObjectName(_fromUtf8("label_et_kc"))
        self.label_ng = QtGui.QLabel(self.group_NecEnerg)
        self.label_ng.setGeometry(QtCore.QRect(30, 250, 141, 17))
        self.label_ng.setObjectName(_fromUtf8("label_ng"))
        self.label_nl = QtGui.QLabel(self.group_NecEnerg)
        self.label_nl.setGeometry(QtCore.QRect(30, 284, 141, 17))
        self.label_nl.setObjectName(_fromUtf8("label_nl"))
        self.label_np = QtGui.QLabel(self.group_NecEnerg)
        self.label_np.setGeometry(QtCore.QRect(30, 316, 141, 17))
        self.label_np.setObjectName(_fromUtf8("label_np"))
        self.lineEdit_NG = QtGui.QLineEdit(self.group_NecEnerg)
        self.lineEdit_NG.setGeometry(QtCore.QRect(223, 245, 140, 27))
        self.lineEdit_NG.setReadOnly(True)
        self.lineEdit_NG.setObjectName(_fromUtf8("lineEdit_NG"))
        self.lineEdit_NL = QtGui.QLineEdit(self.group_NecEnerg)
        self.lineEdit_NL.setGeometry(QtCore.QRect(223, 280, 140, 27))
        self.lineEdit_NL.setReadOnly(True)
        self.lineEdit_NL.setObjectName(_fromUtf8("lineEdit_NL"))
        self.lineEdit_NP = QtGui.QLineEdit(self.group_NecEnerg)
        self.lineEdit_NP.setGeometry(QtCore.QRect(223, 314, 140, 27))
        self.lineEdit_NP.setReadOnly(True)
        self.lineEdit_NP.setObjectName(_fromUtf8("lineEdit_NP"))
        self.label_ng_kc = QtGui.QLabel(self.group_NecEnerg)
        self.label_ng_kc.setGeometry(QtCore.QRect(368, 250, 35, 17))
        self.label_ng_kc.setObjectName(_fromUtf8("label_ng_kc"))
        self.label_nl_kc = QtGui.QLabel(self.group_NecEnerg)
        self.label_nl_kc.setGeometry(QtCore.QRect(368, 284, 35, 17))
        self.label_nl_kc.setObjectName(_fromUtf8("label_nl_kc"))
        self.label_np_kc = QtGui.QLabel(self.group_NecEnerg)
        self.label_np_kc.setGeometry(QtCore.QRect(368, 320, 35, 17))
        self.label_np_kc.setObjectName(_fromUtf8("label_np_kc"))
        self.line_hor = QtGui.QFrame(self.tab_EstAntr)
        self.line_hor.setEnabled(False)
        self.line_hor.setGeometry(QtCore.QRect(0, 350, 881, 5))
        self.line_hor.setFrameShape(QtGui.QFrame.HLine)
        self.line_hor.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_hor.setObjectName(_fromUtf8("line_hor"))
        self.group_Tratam = QtGui.QGroupBox(self.tab_EstAntr)
        self.group_Tratam.setGeometry(QtCore.QRect(10, 360, 868, 131))
        self.group_Tratam.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.group_Tratam.setFlat(False)
        self.group_Tratam.setObjectName(_fromUtf8("group_Tratam"))
        self.treeWidget_tratam = QtGui.QTreeWidget(self.group_Tratam)
        self.treeWidget_tratam.setGeometry(QtCore.QRect(10, 25, 778, 101))
        self.treeWidget_tratam.setTextElideMode(QtCore.Qt.ElideRight)
        self.treeWidget_tratam.setUniformRowHeights(False)
        self.treeWidget_tratam.setObjectName(_fromUtf8("treeWidget_tratam"))
        self.treeWidget_tratam.header().setCascadingSectionResizes(False)
        self.treeWidget_tratam.header().setDefaultSectionSize(194)
        self.treeWidget_tratam.header().setHighlightSections(False)
        self.treeWidget_tratam.header().setMinimumSectionSize(20)
        self.treeWidget_tratam.header().setSortIndicatorShown(False)
        self.treeWidget_tratam.header().setStretchLastSection(False)
        self.pushButton_Anadir = QtGui.QPushButton(self.group_Tratam)
        self.pushButton_Anadir.setGeometry(QtCore.QRect(801, 60, 60, 20))
        self.pushButton_Anadir.setObjectName(_fromUtf8("pushButton_Anadir"))
        self.pushButton_Elim = QtGui.QPushButton(self.group_Tratam)
        self.pushButton_Elim.setGeometry(QtCore.QRect(797, 90, 71, 20))
        self.pushButton_Elim.setObjectName(_fromUtf8("pushButton_Elim"))
        self.tabWidget.addTab(self.tab_EstAntr, _fromUtf8(""))
        self.tab_HistDiet = QtGui.QWidget()
        self.tab_HistDiet.setObjectName(_fromUtf8("tab_HistDiet"))
        self.pushButton_DiDiet = QtGui.QPushButton(self.tab_HistDiet)
        self.pushButton_DiDiet.setGeometry(QtCore.QRect(260, 20, 114, 27))
        self.pushButton_DiDiet.setObjectName(_fromUtf8("pushButton_DiDiet"))
        self.pushButton_Record = QtGui.QPushButton(self.tab_HistDiet)
        self.pushButton_Record.setGeometry(QtCore.QRect(452, 20, 131, 27))
        self.pushButton_Record.setObjectName(_fromUtf8("pushButton_Record"))
        self.pushButton_Cuest = QtGui.QPushButton(self.tab_HistDiet)
        self.pushButton_Cuest.setGeometry(QtCore.QRect(660, 20, 191, 27))
        self.pushButton_Cuest.setObjectName(_fromUtf8("pushButton_Cuest"))
        self.pushButton_InfG = QtGui.QPushButton(self.tab_HistDiet)
        self.pushButton_InfG.setGeometry(QtCore.QRect(31, 20, 154, 27))
        self.pushButton_InfG.setObjectName(_fromUtf8("pushButton_InfG"))
        self.tabWidget.addTab(self.tab_HistDiet, _fromUtf8(""))
        self.tab_RegDiet = QtGui.QWidget()
        self.tab_RegDiet.setObjectName(_fromUtf8("tab_RegDiet"))
        self.label_3 = QtGui.QLabel(self.tab_RegDiet)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 81, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.comboBox = QtGui.QComboBox(self.tab_RegDiet)
        self.comboBox.setGeometry(QtCore.QRect(100, 8, 50, 21))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.stackedWidget = QtGui.QStackedWidget(self.tab_RegDiet)
        self.stackedWidget.setEnabled(False)
        self.stackedWidget.setGeometry(QtCore.QRect(8, 30, 860, 251))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.lineEdit_6_4 = QtGui.QLineEdit(self.page_4)
        self.lineEdit_6_4.setEnabled(False)
        self.lineEdit_6_4.setGeometry(QtCore.QRect(0, 130, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_6_4.setFont(font)
        self.lineEdit_6_4.setReadOnly(True)
        self.lineEdit_6_4.setObjectName(_fromUtf8("lineEdit_6_4"))
        self.lineEdit_6_1 = QtGui.QLineEdit(self.page_4)
        self.lineEdit_6_1.setEnabled(False)
        self.lineEdit_6_1.setGeometry(QtCore.QRect(0, 40, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_6_1.setFont(font)
        self.lineEdit_6_1.setReadOnly(True)
        self.lineEdit_6_1.setObjectName(_fromUtf8("lineEdit_6_1"))
        self.lineEdit_6_2 = QtGui.QLineEdit(self.page_4)
        self.lineEdit_6_2.setEnabled(False)
        self.lineEdit_6_2.setGeometry(QtCore.QRect(0, 70, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_6_2.setFont(font)
        self.lineEdit_6_2.setReadOnly(True)
        self.lineEdit_6_2.setObjectName(_fromUtf8("lineEdit_6_2"))
        self.label_6_1 = QtGui.QLabel(self.page_4)
        self.label_6_1.setEnabled(False)
        self.label_6_1.setGeometry(QtCore.QRect(4, 16, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6_1.setFont(font)
        self.label_6_1.setObjectName(_fromUtf8("label_6_1"))
        self.lineEdit_6_5 = QtGui.QLineEdit(self.page_4)
        self.lineEdit_6_5.setEnabled(False)
        self.lineEdit_6_5.setGeometry(QtCore.QRect(0, 160, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_6_5.setFont(font)
        self.lineEdit_6_5.setReadOnly(True)
        self.lineEdit_6_5.setObjectName(_fromUtf8("lineEdit_6_5"))
        self.lineEdit_6_3 = QtGui.QLineEdit(self.page_4)
        self.lineEdit_6_3.setEnabled(False)
        self.lineEdit_6_3.setGeometry(QtCore.QRect(0, 100, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_6_3.setFont(font)
        self.lineEdit_6_3.setReadOnly(True)
        self.lineEdit_6_3.setObjectName(_fromUtf8("lineEdit_6_3"))
        self.lineEdit_6_7 = QtGui.QLineEdit(self.page_4)
        self.lineEdit_6_7.setEnabled(False)
        self.lineEdit_6_7.setGeometry(QtCore.QRect(170, 220, 81, 27))
        self.lineEdit_6_7.setReadOnly(True)
        self.lineEdit_6_7.setObjectName(_fromUtf8("lineEdit_6_7"))
        self.lineEdit_6_6 = QtGui.QLineEdit(self.page_4)
        self.lineEdit_6_6.setEnabled(False)
        self.lineEdit_6_6.setGeometry(QtCore.QRect(0, 190, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_6_6.setFont(font)
        self.lineEdit_6_6.setReadOnly(True)
        self.lineEdit_6_6.setObjectName(_fromUtf8("lineEdit_6_6"))
        self.lineEdit_6_8 = QtGui.QLineEdit(self.page_4)
        self.lineEdit_6_8.setEnabled(False)
        self.lineEdit_6_8.setGeometry(QtCore.QRect(270, 220, 81, 27))
        self.lineEdit_6_8.setReadOnly(True)
        self.lineEdit_6_8.setObjectName(_fromUtf8("lineEdit_6_8"))
        self.lineEdit_6_9 = QtGui.QLineEdit(self.page_4)
        self.lineEdit_6_9.setEnabled(False)
        self.lineEdit_6_9.setGeometry(QtCore.QRect(370, 220, 81, 27))
        self.lineEdit_6_9.setReadOnly(True)
        self.lineEdit_6_9.setObjectName(_fromUtf8("lineEdit_6_9"))
        self.lineEdit_6_10 = QtGui.QLineEdit(self.page_4)
        self.lineEdit_6_10.setEnabled(False)
        self.lineEdit_6_10.setGeometry(QtCore.QRect(470, 220, 81, 27))
        self.lineEdit_6_10.setReadOnly(True)
        self.lineEdit_6_10.setObjectName(_fromUtf8("lineEdit_6_10"))
        self.lineEdit_6_11 = QtGui.QLineEdit(self.page_4)
        self.lineEdit_6_11.setEnabled(False)
        self.lineEdit_6_11.setGeometry(QtCore.QRect(570, 220, 81, 27))
        self.lineEdit_6_11.setReadOnly(True)
        self.lineEdit_6_11.setObjectName(_fromUtf8("lineEdit_6_11"))
        self.lineEdit_6_12 = QtGui.QLineEdit(self.page_4)
        self.lineEdit_6_12.setEnabled(False)
        self.lineEdit_6_12.setGeometry(QtCore.QRect(670, 220, 81, 27))
        self.lineEdit_6_12.setReadOnly(True)
        self.lineEdit_6_12.setObjectName(_fromUtf8("lineEdit_6_12"))
        self.lineEdit_6_13 = QtGui.QLineEdit(self.page_4)
        self.lineEdit_6_13.setEnabled(False)
        self.lineEdit_6_13.setGeometry(QtCore.QRect(770, 220, 81, 27))
        self.lineEdit_6_13.setReadOnly(True)
        self.lineEdit_6_13.setObjectName(_fromUtf8("lineEdit_6_13"))
        self.push_Kcal_6 = QtGui.QPushButton(self.page_4)
        self.push_Kcal_6.setGeometry(QtCore.QRect(60, 225, 71, 21))
        self.push_Kcal_6.setObjectName(_fromUtf8("push_Kcal_6"))
        self.stackedWidget.addWidget(self.page_4)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.lineEdit_5_4 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_5_4.setGeometry(QtCore.QRect(0, 130, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_5_4.setFont(font)
        self.lineEdit_5_4.setReadOnly(True)
        self.lineEdit_5_4.setObjectName(_fromUtf8("lineEdit_5_4"))
        self.lineEdit_5_1 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_5_1.setGeometry(QtCore.QRect(0, 40, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_5_1.setFont(font)
        self.lineEdit_5_1.setReadOnly(True)
        self.lineEdit_5_1.setObjectName(_fromUtf8("lineEdit_5_1"))
        self.lineEdit_5_2 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_5_2.setGeometry(QtCore.QRect(0, 70, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_5_2.setFont(font)
        self.lineEdit_5_2.setReadOnly(True)
        self.lineEdit_5_2.setObjectName(_fromUtf8("lineEdit_5_2"))
        self.label_5_1 = QtGui.QLabel(self.page_3)
        self.label_5_1.setGeometry(QtCore.QRect(4, 16, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5_1.setFont(font)
        self.label_5_1.setObjectName(_fromUtf8("label_5_1"))
        self.lineEdit_5_5 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_5_5.setGeometry(QtCore.QRect(0, 160, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_5_5.setFont(font)
        self.lineEdit_5_5.setReadOnly(True)
        self.lineEdit_5_5.setObjectName(_fromUtf8("lineEdit_5_5"))
        self.lineEdit_5_3 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_5_3.setGeometry(QtCore.QRect(0, 100, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_5_3.setFont(font)
        self.lineEdit_5_3.setReadOnly(True)
        self.lineEdit_5_3.setObjectName(_fromUtf8("lineEdit_5_3"))
        self.lineEdit_5_6 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_5_6.setGeometry(QtCore.QRect(170, 200, 81, 27))
        self.lineEdit_5_6.setReadOnly(True)
        self.lineEdit_5_6.setObjectName(_fromUtf8("lineEdit_5_6"))
        self.lineEdit_5_7 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_5_7.setGeometry(QtCore.QRect(270, 200, 81, 27))
        self.lineEdit_5_7.setReadOnly(True)
        self.lineEdit_5_7.setObjectName(_fromUtf8("lineEdit_5_7"))
        self.lineEdit_5_8 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_5_8.setGeometry(QtCore.QRect(370, 200, 81, 27))
        self.lineEdit_5_8.setReadOnly(True)
        self.lineEdit_5_8.setObjectName(_fromUtf8("lineEdit_5_8"))
        self.lineEdit_5_9 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_5_9.setGeometry(QtCore.QRect(470, 200, 81, 27))
        self.lineEdit_5_9.setReadOnly(True)
        self.lineEdit_5_9.setObjectName(_fromUtf8("lineEdit_5_9"))
        self.lineEdit_5_10 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_5_10.setGeometry(QtCore.QRect(570, 200, 81, 27))
        self.lineEdit_5_10.setReadOnly(True)
        self.lineEdit_5_10.setObjectName(_fromUtf8("lineEdit_5_10"))
        self.lineEdit_5_11 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_5_11.setGeometry(QtCore.QRect(670, 200, 81, 27))
        self.lineEdit_5_11.setReadOnly(True)
        self.lineEdit_5_11.setObjectName(_fromUtf8("lineEdit_5_11"))
        self.lineEdit_5_12 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_5_12.setGeometry(QtCore.QRect(770, 200, 81, 27))
        self.lineEdit_5_12.setReadOnly(True)
        self.lineEdit_5_12.setObjectName(_fromUtf8("lineEdit_5_12"))
        self.push_Kcal_5 = QtGui.QPushButton(self.page_3)
        self.push_Kcal_5.setGeometry(QtCore.QRect(60, 205, 71, 21))
        self.push_Kcal_5.setObjectName(_fromUtf8("push_Kcal_5"))
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.lineEdit_4_1 = QtGui.QLineEdit(self.page_2)
        self.lineEdit_4_1.setGeometry(QtCore.QRect(10, 70, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_4_1.setFont(font)
        self.lineEdit_4_1.setReadOnly(True)
        self.lineEdit_4_1.setObjectName(_fromUtf8("lineEdit_4_1"))
        self.lineEdit_4_2 = QtGui.QLineEdit(self.page_2)
        self.lineEdit_4_2.setGeometry(QtCore.QRect(10, 100, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_4_2.setFont(font)
        self.lineEdit_4_2.setReadOnly(True)
        self.lineEdit_4_2.setObjectName(_fromUtf8("lineEdit_4_2"))
        self.label_4_1 = QtGui.QLabel(self.page_2)
        self.label_4_1.setGeometry(QtCore.QRect(14, 46, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4_1.setFont(font)
        self.label_4_1.setObjectName(_fromUtf8("label_4_1"))
        self.lineEdit_4_3 = QtGui.QLineEdit(self.page_2)
        self.lineEdit_4_3.setGeometry(QtCore.QRect(10, 130, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_4_3.setFont(font)
        self.lineEdit_4_3.setReadOnly(True)
        self.lineEdit_4_3.setObjectName(_fromUtf8("lineEdit_4_3"))
        self.lineEdit_4_5 = QtGui.QLineEdit(self.page_2)
        self.lineEdit_4_5.setGeometry(QtCore.QRect(150, 200, 81, 27))
        self.lineEdit_4_5.setReadOnly(True)
        self.lineEdit_4_5.setObjectName(_fromUtf8("lineEdit_4_5"))
        self.lineEdit_4_4 = QtGui.QLineEdit(self.page_2)
        self.lineEdit_4_4.setGeometry(QtCore.QRect(10, 160, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_4_4.setFont(font)
        self.lineEdit_4_4.setReadOnly(True)
        self.lineEdit_4_4.setObjectName(_fromUtf8("lineEdit_4_4"))
        self.lineEdit_4_6 = QtGui.QLineEdit(self.page_2)
        self.lineEdit_4_6.setGeometry(QtCore.QRect(250, 200, 81, 27))
        self.lineEdit_4_6.setReadOnly(True)
        self.lineEdit_4_6.setObjectName(_fromUtf8("lineEdit_4_6"))
        self.lineEdit_4_7 = QtGui.QLineEdit(self.page_2)
        self.lineEdit_4_7.setGeometry(QtCore.QRect(350, 200, 81, 27))
        self.lineEdit_4_7.setReadOnly(True)
        self.lineEdit_4_7.setObjectName(_fromUtf8("lineEdit_4_7"))
        self.lineEdit_4_8 = QtGui.QLineEdit(self.page_2)
        self.lineEdit_4_8.setGeometry(QtCore.QRect(450, 200, 81, 27))
        self.lineEdit_4_8.setReadOnly(True)
        self.lineEdit_4_8.setObjectName(_fromUtf8("lineEdit_4_8"))
        self.lineEdit_4_9 = QtGui.QLineEdit(self.page_2)
        self.lineEdit_4_9.setGeometry(QtCore.QRect(550, 200, 81, 27))
        self.lineEdit_4_9.setReadOnly(True)
        self.lineEdit_4_9.setObjectName(_fromUtf8("lineEdit_4_9"))
        self.lineEdit_4_10 = QtGui.QLineEdit(self.page_2)
        self.lineEdit_4_10.setGeometry(QtCore.QRect(650, 200, 81, 27))
        self.lineEdit_4_10.setReadOnly(True)
        self.lineEdit_4_10.setObjectName(_fromUtf8("lineEdit_4_10"))
        self.lineEdit_4_11 = QtGui.QLineEdit(self.page_2)
        self.lineEdit_4_11.setGeometry(QtCore.QRect(750, 200, 81, 27))
        self.lineEdit_4_11.setReadOnly(True)
        self.lineEdit_4_11.setObjectName(_fromUtf8("lineEdit_4_11"))
        self.push_Kcal_4 = QtGui.QPushButton(self.page_2)
        self.push_Kcal_4.setGeometry(QtCore.QRect(60, 205, 71, 21))
        self.push_Kcal_4.setObjectName(_fromUtf8("push_Kcal_4"))
        self.stackedWidget.addWidget(self.page_2)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.lineEdit_3_3 = QtGui.QLineEdit(self.page)
        self.lineEdit_3_3.setGeometry(QtCore.QRect(10, 140, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_3_3.setFont(font)
        self.lineEdit_3_3.setReadOnly(True)
        self.lineEdit_3_3.setObjectName(_fromUtf8("lineEdit_3_3"))
        self.lineEdit_3_1 = QtGui.QLineEdit(self.page)
        self.lineEdit_3_1.setGeometry(QtCore.QRect(10, 80, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_3_1.setFont(font)
        self.lineEdit_3_1.setReadOnly(True)
        self.lineEdit_3_1.setObjectName(_fromUtf8("lineEdit_3_1"))
        self.lineEdit_3_2 = QtGui.QLineEdit(self.page)
        self.lineEdit_3_2.setGeometry(QtCore.QRect(10, 110, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_3_2.setFont(font)
        self.lineEdit_3_2.setReadOnly(True)
        self.lineEdit_3_2.setObjectName(_fromUtf8("lineEdit_3_2"))
        self.label_3_1 = QtGui.QLabel(self.page)
        self.label_3_1.setGeometry(QtCore.QRect(14, 56, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3_1.setFont(font)
        self.label_3_1.setObjectName(_fromUtf8("label_3_1"))
        self.lineEdit_3_4 = QtGui.QLineEdit(self.page)
        self.lineEdit_3_4.setGeometry(QtCore.QRect(150, 190, 81, 27))
        self.lineEdit_3_4.setReadOnly(True)
        self.lineEdit_3_4.setObjectName(_fromUtf8("lineEdit_3_4"))
        self.lineEdit_3_5 = QtGui.QLineEdit(self.page)
        self.lineEdit_3_5.setGeometry(QtCore.QRect(250, 190, 81, 27))
        self.lineEdit_3_5.setReadOnly(True)
        self.lineEdit_3_5.setObjectName(_fromUtf8("lineEdit_3_5"))
        self.lineEdit_3_6 = QtGui.QLineEdit(self.page)
        self.lineEdit_3_6.setGeometry(QtCore.QRect(350, 190, 81, 27))
        self.lineEdit_3_6.setReadOnly(True)
        self.lineEdit_3_6.setObjectName(_fromUtf8("lineEdit_3_6"))
        self.lineEdit_3_7 = QtGui.QLineEdit(self.page)
        self.lineEdit_3_7.setGeometry(QtCore.QRect(450, 190, 81, 27))
        self.lineEdit_3_7.setReadOnly(True)
        self.lineEdit_3_7.setObjectName(_fromUtf8("lineEdit_3_7"))
        self.lineEdit_3_8 = QtGui.QLineEdit(self.page)
        self.lineEdit_3_8.setGeometry(QtCore.QRect(550, 190, 81, 27))
        self.lineEdit_3_8.setReadOnly(True)
        self.lineEdit_3_8.setObjectName(_fromUtf8("lineEdit_3_8"))
        self.lineEdit_3_9 = QtGui.QLineEdit(self.page)
        self.lineEdit_3_9.setGeometry(QtCore.QRect(650, 190, 81, 27))
        self.lineEdit_3_9.setReadOnly(True)
        self.lineEdit_3_9.setObjectName(_fromUtf8("lineEdit_3_9"))
        self.lineEdit_3_10 = QtGui.QLineEdit(self.page)
        self.lineEdit_3_10.setGeometry(QtCore.QRect(750, 190, 81, 27))
        self.lineEdit_3_10.setReadOnly(True)
        self.lineEdit_3_10.setObjectName(_fromUtf8("lineEdit_3_10"))
        self.push_Kcal_3 = QtGui.QPushButton(self.page)
        self.push_Kcal_3.setGeometry(QtCore.QRect(60, 195, 71, 21))
        self.push_Kcal_3.setObjectName(_fromUtf8("push_Kcal_3"))
        self.stackedWidget.addWidget(self.page)
        self.treeWidget = QtGui.QTreeWidget(self.tab_RegDiet)
        self.treeWidget.setGeometry(QtCore.QRect(10, 280, 860, 216))
        self.treeWidget.setMidLineWidth(1)
        self.treeWidget.setDragEnabled(True)
        self.treeWidget.setDragDropOverwriteMode(True)
        self.treeWidget.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.treeWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.treeWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.treeWidget.setIndentation(20)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.treeWidget.header().setDefaultSectionSize(429)
        self.treeWidget.header().setHighlightSections(False)
        self.treeWidget.header().setMinimumSectionSize(230)
        self.treeWidget.header().setStretchLastSection(False)
        self.push_VerRecetas = QtGui.QPushButton(self.tab_RegDiet)
        self.push_VerRecetas.setGeometry(QtCore.QRect(770, 4, 98, 21))
        self.push_VerRecetas.setObjectName(_fromUtf8("push_VerRecetas"))
        self.tabWidget.addTab(self.tab_RegDiet, _fromUtf8(""))
        self.toolButton = QtGui.QToolButton(self.centralwidget)
        self.toolButton.setEnabled(False)
        self.toolButton.setGeometry(QtCore.QRect(872, 3, 26, 22))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 3, 260, 22))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 3, 30, 22))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(325, 8, 35, 14))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(753, 8, 62, 14))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit_3 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(819, 3, 49, 22))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(698, 3, 49, 22))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(611, 8, 82, 14))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 908, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setAutoFillBackground(False)
        self.menuArchivo.setStyleSheet(_fromUtf8(""))
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        self.menuPacientes = QtGui.QMenu(self.menubar)
        self.menuPacientes.setEnabled(True)
        self.menuPacientes.setObjectName(_fromUtf8("menuPacientes"))
        self.menuRecetas = QtGui.QMenu(self.menubar)
        self.menuRecetas.setObjectName(_fromUtf8("menuRecetas"))
        self.menuAcerca_de = QtGui.QMenu(self.menubar)
        self.menuAcerca_de.setObjectName(_fromUtf8("menuAcerca_de"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalir = QtGui.QAction(MainWindow)
        self.actionSalir.setObjectName(_fromUtf8("actionSalir"))
        self.actionDietista = QtGui.QAction(MainWindow)
        self.actionDietista.setEnabled(True)
        self.actionDietista.setObjectName(_fromUtf8("actionDietista"))
        self.actionNuevo_Paciente = QtGui.QAction(MainWindow)
        self.actionNuevo_Paciente.setEnabled(False)
        self.actionNuevo_Paciente.setObjectName(_fromUtf8("actionNuevo_Paciente"))
        self.actionAbrir_Paciente = QtGui.QAction(MainWindow)
        self.actionAbrir_Paciente.setEnabled(False)
        self.actionAbrir_Paciente.setObjectName(_fromUtf8("actionAbrir_Paciente"))
        self.actionNueva_Receta = QtGui.QAction(MainWindow)
        self.actionNueva_Receta.setEnabled(False)
        self.actionNueva_Receta.setIconVisibleInMenu(False)
        self.actionNueva_Receta.setObjectName(_fromUtf8("actionNueva_Receta"))
        self.actionEditar_Receta = QtGui.QAction(MainWindow)
        self.actionEditar_Receta.setEnabled(False)
        self.actionEditar_Receta.setObjectName(_fromUtf8("actionEditar_Receta"))
        self.actionManual = QtGui.QAction(MainWindow)
        self.actionManual.setObjectName(_fromUtf8("actionManual"))
        self.actionAcerca_de = QtGui.QAction(MainWindow)
        self.actionAcerca_de.setObjectName(_fromUtf8("actionAcerca_de"))
        self.actionCerrar_Paciente = QtGui.QAction(MainWindow)
        self.actionCerrar_Paciente.setEnabled(False)
        self.actionCerrar_Paciente.setObjectName(_fromUtf8("actionCerrar_Paciente"))
        self.actionEliminar_Paciente = QtGui.QAction(MainWindow)
        self.actionEliminar_Paciente.setEnabled(False)
        self.actionEliminar_Paciente.setObjectName(_fromUtf8("actionEliminar_Paciente"))
        self.actionCerrar_Perfil = QtGui.QAction(MainWindow)
        self.actionCerrar_Perfil.setCheckable(False)
        self.actionCerrar_Perfil.setEnabled(False)
        self.actionCerrar_Perfil.setObjectName(_fromUtf8("actionCerrar_Perfil"))
        self.actionImprimir = QtGui.QAction(MainWindow)
        self.actionImprimir.setEnabled(False)
        self.actionImprimir.setObjectName(_fromUtf8("actionImprimir"))
        self.actionGuardar = QtGui.QAction(MainWindow)
        self.actionGuardar.setEnabled(False)
        self.actionGuardar.setObjectName(_fromUtf8("actionGuardar"))
        self.actionEliminar_Receta = QtGui.QAction(MainWindow)
        self.actionEliminar_Receta.setEnabled(False)
        self.actionEliminar_Receta.setIconVisibleInMenu(False)
        self.actionEliminar_Receta.setObjectName(_fromUtf8("actionEliminar_Receta"))
        self.menuArchivo.addAction(self.actionDietista)
        self.menuArchivo.addAction(self.actionCerrar_Perfil)
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionImprimir)
        self.menuArchivo.addAction(self.actionSalir)
        self.menuPacientes.addAction(self.actionNuevo_Paciente)
        self.menuPacientes.addAction(self.actionAbrir_Paciente)
        self.menuPacientes.addAction(self.actionCerrar_Paciente)
        self.menuPacientes.addAction(self.actionEliminar_Paciente)
        self.menuRecetas.addAction(self.actionNueva_Receta)
        self.menuRecetas.addAction(self.actionEditar_Receta)
        self.menuRecetas.addAction(self.actionEliminar_Receta)
        self.menuAcerca_de.addAction(self.actionManual)
        self.menuAcerca_de.addAction(self.actionAcerca_de)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuPacientes.menuAction())
        self.menubar.addAction(self.menuRecetas.menuAction())
        self.menubar.addAction(self.menuAcerca_de.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionSalir, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QObject.connect(self.comboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.stackedWidget.setCurrentIndex)
        QtCore.QObject.connect(self.lineEdit_Edad, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), self.lineEdit_2.setText)
        QtCore.QObject.connect(self.doubleSpin_POb, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), self.lineEdit_3.setText)
        QtCore.QObject.connect(self.doubleSpin_Peso, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), self.lineEdit_4.setText)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.combo_FM)
        MainWindow.setTabOrder(self.combo_FM, self.lineEdit_Nom)
        MainWindow.setTabOrder(self.lineEdit_Nom, self.lineEdit_Apell)
        MainWindow.setTabOrder(self.lineEdit_Apell, self.date_FNac)
        MainWindow.setTabOrder(self.date_FNac, self.lineEdit_Edad)
        MainWindow.setTabOrder(self.lineEdit_Edad, self.lineEdit_Dni)
        MainWindow.setTabOrder(self.lineEdit_Dni, self.lineEdit_Dir)
        MainWindow.setTabOrder(self.lineEdit_Dir, self.lineEdit_Prof)
        MainWindow.setTabOrder(self.lineEdit_Prof, self.lineEdit_Tlf)
        MainWindow.setTabOrder(self.lineEdit_Tlf, self.pushButton_InfMed)
        MainWindow.setTabOrder(self.pushButton_InfMed, self.doubleSpin_Peso)
        MainWindow.setTabOrder(self.doubleSpin_Peso, self.doubleSpin_IMC)
        MainWindow.setTabOrder(self.doubleSpin_IMC, self.toolButton_Grado)
        MainWindow.setTabOrder(self.toolButton_Grado, self.doubleSpin_Alt)
        MainWindow.setTabOrder(self.doubleSpin_Alt, self.doubleSpin_POb)
        MainWindow.setTabOrder(self.doubleSpin_POb, self.doubleSpin_Cad)
        MainWindow.setTabOrder(self.doubleSpin_Cad, self.doubleSpin_Cint)
        MainWindow.setTabOrder(self.doubleSpin_Cint, self.doubleSpin_Tricip)
        MainWindow.setTabOrder(self.doubleSpin_Tricip, self.combo_Complex)
        MainWindow.setTabOrder(self.combo_Complex, self.lineEdit_PIdeal)
        MainWindow.setTabOrder(self.lineEdit_PIdeal, self.doubleSpin_PPac)
        MainWindow.setTabOrder(self.doubleSpin_PPac, self.doubleSpin_PMG)
        MainWindow.setTabOrder(self.doubleSpin_PMG, self.doubleSpin_PL)
        MainWindow.setTabOrder(self.doubleSpin_PL, self.doubleSpin_MB)
        MainWindow.setTabOrder(self.doubleSpin_MB, self.combo_Activ)
        MainWindow.setTabOrder(self.combo_Activ, self.doubleSpin_Increm)
        MainWindow.setTabOrder(self.doubleSpin_Increm, self.doubleSpin_Reduc)
        MainWindow.setTabOrder(self.doubleSpin_Reduc, self.doubleSpin_ET)
        MainWindow.setTabOrder(self.doubleSpin_ET, self.lineEdit_NG)
        MainWindow.setTabOrder(self.lineEdit_NG, self.lineEdit_NL)
        MainWindow.setTabOrder(self.lineEdit_NL, self.lineEdit_NP)
        MainWindow.setTabOrder(self.lineEdit_NP, self.treeWidget_tratam)
        MainWindow.setTabOrder(self.treeWidget_tratam, self.pushButton_Anadir)
        MainWindow.setTabOrder(self.pushButton_Anadir, self.pushButton_Elim)
        MainWindow.setTabOrder(self.pushButton_Elim, self.pushButton_InfG)
        MainWindow.setTabOrder(self.pushButton_InfG, self.pushButton_DiDiet)
        MainWindow.setTabOrder(self.pushButton_DiDiet, self.pushButton_Record)
        MainWindow.setTabOrder(self.pushButton_Record, self.pushButton_Cuest)
        MainWindow.setTabOrder(self.pushButton_Cuest, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.lineEdit_6_1)
        MainWindow.setTabOrder(self.lineEdit_6_1, self.lineEdit_6_2)
        MainWindow.setTabOrder(self.lineEdit_6_2, self.lineEdit_6_3)
        MainWindow.setTabOrder(self.lineEdit_6_3, self.lineEdit_6_4)
        MainWindow.setTabOrder(self.lineEdit_6_4, self.lineEdit_6_5)
        MainWindow.setTabOrder(self.lineEdit_6_5, self.lineEdit_6_6)
        MainWindow.setTabOrder(self.lineEdit_6_6, self.lineEdit_6_7)
        MainWindow.setTabOrder(self.lineEdit_6_7, self.lineEdit_6_8)
        MainWindow.setTabOrder(self.lineEdit_6_8, self.lineEdit_6_9)
        MainWindow.setTabOrder(self.lineEdit_6_9, self.lineEdit_6_10)
        MainWindow.setTabOrder(self.lineEdit_6_10, self.lineEdit_6_11)
        MainWindow.setTabOrder(self.lineEdit_6_11, self.lineEdit_6_12)
        MainWindow.setTabOrder(self.lineEdit_6_12, self.lineEdit_6_13)
        MainWindow.setTabOrder(self.lineEdit_6_13, self.lineEdit_5_1)
        MainWindow.setTabOrder(self.lineEdit_5_1, self.lineEdit_5_2)
        MainWindow.setTabOrder(self.lineEdit_5_2, self.lineEdit_5_3)
        MainWindow.setTabOrder(self.lineEdit_5_3, self.lineEdit_5_4)
        MainWindow.setTabOrder(self.lineEdit_5_4, self.lineEdit_5_5)
        MainWindow.setTabOrder(self.lineEdit_5_5, self.lineEdit_5_6)
        MainWindow.setTabOrder(self.lineEdit_5_6, self.lineEdit_5_7)
        MainWindow.setTabOrder(self.lineEdit_5_7, self.lineEdit_5_8)
        MainWindow.setTabOrder(self.lineEdit_5_8, self.lineEdit_5_9)
        MainWindow.setTabOrder(self.lineEdit_5_9, self.lineEdit_5_10)
        MainWindow.setTabOrder(self.lineEdit_5_10, self.lineEdit_5_11)
        MainWindow.setTabOrder(self.lineEdit_5_11, self.lineEdit_5_12)
        MainWindow.setTabOrder(self.lineEdit_5_12, self.lineEdit_4_1)
        MainWindow.setTabOrder(self.lineEdit_4_1, self.lineEdit_4_2)
        MainWindow.setTabOrder(self.lineEdit_4_2, self.lineEdit_4_5)
        MainWindow.setTabOrder(self.lineEdit_4_5, self.lineEdit_4_3)
        MainWindow.setTabOrder(self.lineEdit_4_3, self.lineEdit_4_4)
        MainWindow.setTabOrder(self.lineEdit_4_4, self.lineEdit_4_6)
        MainWindow.setTabOrder(self.lineEdit_4_6, self.lineEdit_4_7)
        MainWindow.setTabOrder(self.lineEdit_4_7, self.lineEdit_4_8)
        MainWindow.setTabOrder(self.lineEdit_4_8, self.lineEdit_4_9)
        MainWindow.setTabOrder(self.lineEdit_4_9, self.lineEdit_4_10)
        MainWindow.setTabOrder(self.lineEdit_4_10, self.lineEdit_4_11)
        MainWindow.setTabOrder(self.lineEdit_4_11, self.lineEdit_3_1)
        MainWindow.setTabOrder(self.lineEdit_3_1, self.lineEdit_3_2)
        MainWindow.setTabOrder(self.lineEdit_3_2, self.lineEdit_3_3)
        MainWindow.setTabOrder(self.lineEdit_3_3, self.lineEdit_3_4)
        MainWindow.setTabOrder(self.lineEdit_3_4, self.lineEdit_3_5)
        MainWindow.setTabOrder(self.lineEdit_3_5, self.lineEdit_3_6)
        MainWindow.setTabOrder(self.lineEdit_3_6, self.lineEdit_3_7)
        MainWindow.setTabOrder(self.lineEdit_3_7, self.lineEdit_3_8)
        MainWindow.setTabOrder(self.lineEdit_3_8, self.lineEdit_3_9)
        MainWindow.setTabOrder(self.lineEdit_3_9, self.lineEdit_3_10)
        MainWindow.setTabOrder(self.lineEdit_3_10, self.treeWidget)
        MainWindow.setTabOrder(self.treeWidget, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.toolButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Estudio Dietético Programado 2011", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_InfMed.setText(QtGui.QApplication.translate("MainWindow", "Información Médica", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nom.setText(QtGui.QApplication.translate("MainWindow", "Nombre :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_apell.setText(QtGui.QApplication.translate("MainWindow", "Apellidos :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_edad.setText(QtGui.QApplication.translate("MainWindow", "Edad :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sexo.setText(QtGui.QApplication.translate("MainWindow", "Sexo :", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_FM.setItemText(0, QtGui.QApplication.translate("MainWindow", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_FM.setItemText(1, QtGui.QApplication.translate("MainWindow", "M", None, QtGui.QApplication.UnicodeUTF8))
        self.date_FNac.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_FNac.setText(QtGui.QApplication.translate("MainWindow", "Fch. Nacimiento :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_dni.setText(QtGui.QApplication.translate("MainWindow", "D.N.I. :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_dir.setText(QtGui.QApplication.translate("MainWindow", "Dirección:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_prof.setText(QtGui.QApplication.translate("MainWindow", "Profesión :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tlf.setText(QtGui.QApplication.translate("MainWindow", "Teléfono :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "años", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_DatosPers), QtGui.QApplication.translate("MainWindow", "Datos Personales", None, QtGui.QApplication.UnicodeUTF8))
        self.group_Antr.setTitle(QtGui.QApplication.translate("MainWindow", "Antropometría", None, QtGui.QApplication.UnicodeUTF8))
        self.label_peso.setText(QtGui.QApplication.translate("MainWindow", "Peso:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_peso_kg.setText(QtGui.QApplication.translate("MainWindow", "Kg.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_altura.setText(QtGui.QApplication.translate("MainWindow", "Altura:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_alt_cm.setText(QtGui.QApplication.translate("MainWindow", "cm.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_imc.setText(QtGui.QApplication.translate("MainWindow", "I.M.C. :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pob.setText(QtGui.QApplication.translate("MainWindow", "Objetivo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_porc.setText(QtGui.QApplication.translate("MainWindow", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pob_kg.setText(QtGui.QApplication.translate("MainWindow", "Kg.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_complex.setText(QtGui.QApplication.translate("MainWindow", "Complexión:", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_Complex.setItemText(0, QtGui.QApplication.translate("MainWindow", "Delgada", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_Complex.setItemText(1, QtGui.QApplication.translate("MainWindow", "Media", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_Complex.setItemText(2, QtGui.QApplication.translate("MainWindow", "Ancha", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cint.setText(QtGui.QApplication.translate("MainWindow", "Cintura:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cader.setText(QtGui.QApplication.translate("MainWindow", "Cadera:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tricip.setText(QtGui.QApplication.translate("MainWindow", "Pliegue Tricipital:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cad_cm.setText(QtGui.QApplication.translate("MainWindow", "cm.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cint_cm.setText(QtGui.QApplication.translate("MainWindow", "cm.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pideal.setText(QtGui.QApplication.translate("MainWindow", "Peso ideal:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tr_cm.setText(QtGui.QApplication.translate("MainWindow", "cm.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pesoi_kg.setText(QtGui.QApplication.translate("MainWindow", "Kg.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_PMG.setText(QtGui.QApplication.translate("MainWindow", "Pérdida Materia Grasa:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_PL.setText(QtGui.QApplication.translate("MainWindow", "Pérdida Líquidos:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_porc_2.setText(QtGui.QApplication.translate("MainWindow", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_porc_3.setText(QtGui.QApplication.translate("MainWindow", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_PPac.setText(QtGui.QApplication.translate("MainWindow", "Peso Pactado:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ppac_kg.setText(QtGui.QApplication.translate("MainWindow", "Kg.", None, QtGui.QApplication.UnicodeUTF8))
        self.group_NecEnerg.setTitle(QtGui.QApplication.translate("MainWindow", "Necesidades Energéticas", None, QtGui.QApplication.UnicodeUTF8))
        self.label_mb.setText(QtGui.QApplication.translate("MainWindow", "Metabolismo Basal:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_activ.setText(QtGui.QApplication.translate("MainWindow", "Actividad:", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_Activ.setItemText(0, QtGui.QApplication.translate("MainWindow", "Ligera", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_Activ.setItemText(1, QtGui.QApplication.translate("MainWindow", "Moderada", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_Activ.setItemText(2, QtGui.QApplication.translate("MainWindow", "Intensa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_increm.setText(QtGui.QApplication.translate("MainWindow", "Incremento por Actividad:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_reduc.setText(QtGui.QApplication.translate("MainWindow", "Reducción según Edad:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_et.setText(QtGui.QApplication.translate("MainWindow", "Energía Total:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_mb_kc.setText(QtGui.QApplication.translate("MainWindow", "Kcal.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_incr_kc.setText(QtGui.QApplication.translate("MainWindow", "Kcal.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_reduc_kc.setText(QtGui.QApplication.translate("MainWindow", "Kcal.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_et_kc.setText(QtGui.QApplication.translate("MainWindow", "Kcal.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ng.setText(QtGui.QApplication.translate("MainWindow", "Necesidad Glucídica:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nl.setText(QtGui.QApplication.translate("MainWindow", "Necesidad Lipídica:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_np.setText(QtGui.QApplication.translate("MainWindow", "Necesidad Proteica:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ng_kc.setText(QtGui.QApplication.translate("MainWindow", "Kcal.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nl_kc.setText(QtGui.QApplication.translate("MainWindow", "Kcal.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_np_kc.setText(QtGui.QApplication.translate("MainWindow", "Kcal.", None, QtGui.QApplication.UnicodeUTF8))
        self.group_Tratam.setTitle(QtGui.QApplication.translate("MainWindow", "Tratamiento de Apoyo", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_tratam.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Fecha", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_tratam.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Tratamiento", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_tratam.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Posología", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_tratam.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Observaciones", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Anadir.setText(QtGui.QApplication.translate("MainWindow", "Añadir", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Elim.setText(QtGui.QApplication.translate("MainWindow", "Eliminar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_EstAntr), QtGui.QApplication.translate("MainWindow", "Estudio Antropométrico", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_DiDiet.setText(QtGui.QApplication.translate("MainWindow", "Diario Dietético", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Record.setText(QtGui.QApplication.translate("MainWindow", "Recordatorio 24 h.", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Cuest.setText(QtGui.QApplication.translate("MainWindow", "Cuestionario de Frecuencia", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_InfG.setText(QtGui.QApplication.translate("MainWindow", "Información General", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_HistDiet), QtGui.QApplication.translate("MainWindow", "Historia Dietética", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Nº Ingestas:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6_1.setText(QtGui.QApplication.translate("MainWindow", "Kcal./%", None, QtGui.QApplication.UnicodeUTF8))
        self.push_Kcal_6.setText(QtGui.QApplication.translate("MainWindow", "Kcal./día:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5_1.setText(QtGui.QApplication.translate("MainWindow", "Kcal./%", None, QtGui.QApplication.UnicodeUTF8))
        self.push_Kcal_5.setText(QtGui.QApplication.translate("MainWindow", "Kcal./día:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4_1.setText(QtGui.QApplication.translate("MainWindow", "Kcal./%", None, QtGui.QApplication.UnicodeUTF8))
        self.push_Kcal_4.setText(QtGui.QApplication.translate("MainWindow", "Kcal./día:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3_1.setText(QtGui.QApplication.translate("MainWindow", "Kcal./%", None, QtGui.QApplication.UnicodeUTF8))
        self.push_Kcal_3.setText(QtGui.QApplication.translate("MainWindow", "Kcal./día:", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Recetas", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Calorías", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "Desayuno", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).setText(0, QtGui.QApplication.translate("MainWindow", "Media Mañana", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(2).setText(0, QtGui.QApplication.translate("MainWindow", "Almuerzo", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(3).setText(0, QtGui.QApplication.translate("MainWindow", "Merienda", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(4).setText(0, QtGui.QApplication.translate("MainWindow", "Cena", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(5).setText(0, QtGui.QApplication.translate("MainWindow", "Tentempié", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.push_VerRecetas.setText(QtGui.QApplication.translate("MainWindow", "Ver Recetas", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_RegDiet), QtGui.QApplication.translate("MainWindow", "Registro Dietético", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "!!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "años", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Objetivo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Peso Actual:", None, QtGui.QApplication.UnicodeUTF8))
        self.menuArchivo.setTitle(QtGui.QApplication.translate("MainWindow", "Archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPacientes.setTitle(QtGui.QApplication.translate("MainWindow", "Paciente", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRecetas.setTitle(QtGui.QApplication.translate("MainWindow", "Recetas", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAcerca_de.setTitle(QtGui.QApplication.translate("MainWindow", "Ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalir.setText(QtGui.QApplication.translate("MainWindow", "Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDietista.setText(QtGui.QApplication.translate("MainWindow", "Abrir Perfil Dietista", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevo_Paciente.setText(QtGui.QApplication.translate("MainWindow", "Nuevo Paciente", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbrir_Paciente.setText(QtGui.QApplication.translate("MainWindow", "Abrir Paciente", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNueva_Receta.setText(QtGui.QApplication.translate("MainWindow", "Nueva Receta", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditar_Receta.setText(QtGui.QApplication.translate("MainWindow", "Editar Receta", None, QtGui.QApplication.UnicodeUTF8))
        self.actionManual.setText(QtGui.QApplication.translate("MainWindow", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAcerca_de.setText(QtGui.QApplication.translate("MainWindow", "Acerca de", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCerrar_Paciente.setText(QtGui.QApplication.translate("MainWindow", "Cerrar Paciente", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEliminar_Paciente.setText(QtGui.QApplication.translate("MainWindow", "Eliminar Paciente", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCerrar_Perfil.setText(QtGui.QApplication.translate("MainWindow", "Cerrar Perfil", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImprimir.setText(QtGui.QApplication.translate("MainWindow", "Imprimir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGuardar.setText(QtGui.QApplication.translate("MainWindow", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEliminar_Receta.setText(QtGui.QApplication.translate("MainWindow", "Eliminar Receta", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

