# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/infogen.ui'
#
# Created: Fri May  4 20:47:52 2012
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog_InfoGen(object):
    def setupUi(self, Dialog_InfoGen):
        Dialog_InfoGen.setObjectName("Dialog_InfoGen")
        Dialog_InfoGen.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_InfoGen.resize(676, 482)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog_InfoGen)
        self.buttonBox.setGeometry(QtCore.QRect(10, 440, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.scrollArea = QtGui.QScrollArea(Dialog_InfoGen)
        self.scrollArea.setGeometry(QtCore.QRect(2, 2, 671, 421))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 653, 1742))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(self.widget)
        self.groupBox.setMinimumSize(QtCore.QSize(630, 161))
        self.groupBox.setObjectName("groupBox")
        self.tableWidget = QtGui.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(10, 30, 611, 122))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.widget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(630, 160))
        self.groupBox_2.setObjectName("groupBox_2")
        self.tableWidget_2 = QtGui.QTableWidget(self.groupBox_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 30, 611, 122))
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 0, item)
        self.tableWidget_2.horizontalHeader().setVisible(False)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.widget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(630, 129))
        self.groupBox_3.setObjectName("groupBox_3")
        self.tableWidget_3 = QtGui.QTableWidget(self.groupBox_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 30, 611, 92))
        self.tableWidget_3.setShowGrid(True)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 0, item)
        self.tableWidget_3.horizontalHeader().setVisible(False)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.widget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(630, 217))
        self.groupBox_4.setObjectName("groupBox_4")
        self.tableWidget_4 = QtGui.QTableWidget(self.groupBox_4)
        self.tableWidget_4.setGeometry(QtCore.QRect(10, 30, 611, 182))
        self.tableWidget_4.setShowGrid(True)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(1)
        self.tableWidget_4.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(5, 0, item)
        self.tableWidget_4.horizontalHeader().setVisible(False)
        self.tableWidget_4.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(self.widget)
        self.groupBox_5.setMinimumSize(QtCore.QSize(630, 127))
        self.groupBox_5.setObjectName("groupBox_5")
        self.tableWidget_5 = QtGui.QTableWidget(self.groupBox_5)
        self.tableWidget_5.setGeometry(QtCore.QRect(10, 30, 611, 92))
        self.tableWidget_5.setShowGrid(True)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(1)
        self.tableWidget_5.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setItem(2, 0, item)
        self.tableWidget_5.horizontalHeader().setVisible(False)
        self.tableWidget_5.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.widget)
        self.groupBox_6.setMinimumSize(QtCore.QSize(630, 97))
        self.groupBox_6.setObjectName("groupBox_6")
        self.tableWidget_6 = QtGui.QTableWidget(self.groupBox_6)
        self.tableWidget_6.setGeometry(QtCore.QRect(10, 30, 611, 62))
        self.tableWidget_6.setShowGrid(True)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(1)
        self.tableWidget_6.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setItem(1, 0, item)
        self.tableWidget_6.horizontalHeader().setVisible(False)
        self.tableWidget_6.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.groupBox_7 = QtGui.QGroupBox(self.widget)
        self.groupBox_7.setMinimumSize(QtCore.QSize(630, 127))
        self.groupBox_7.setObjectName("groupBox_7")
        self.tableWidget_7 = QtGui.QTableWidget(self.groupBox_7)
        self.tableWidget_7.setGeometry(QtCore.QRect(10, 30, 611, 92))
        self.tableWidget_7.setShowGrid(True)
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(1)
        self.tableWidget_7.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_7.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_7.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_7.setItem(2, 0, item)
        self.tableWidget_7.horizontalHeader().setVisible(False)
        self.tableWidget_7.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.widget)
        self.groupBox_8.setMinimumSize(QtCore.QSize(630, 126))
        self.groupBox_8.setObjectName("groupBox_8")
        self.tableWidget_8 = QtGui.QTableWidget(self.groupBox_8)
        self.tableWidget_8.setGeometry(QtCore.QRect(10, 30, 611, 92))
        self.tableWidget_8.setShowGrid(True)
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(1)
        self.tableWidget_8.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_8.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_8.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_8.setItem(2, 0, item)
        self.tableWidget_8.horizontalHeader().setVisible(False)
        self.tableWidget_8.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.groupBox_8)
        self.groupBox_9 = QtGui.QGroupBox(self.widget)
        self.groupBox_9.setMinimumSize(QtCore.QSize(630, 159))
        self.groupBox_9.setObjectName("groupBox_9")
        self.tableWidget_9 = QtGui.QTableWidget(self.groupBox_9)
        self.tableWidget_9.setGeometry(QtCore.QRect(10, 30, 611, 122))
        self.tableWidget_9.setShowGrid(True)
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.setColumnCount(1)
        self.tableWidget_9.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_9.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_9.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_9.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_9.setItem(3, 0, item)
        self.tableWidget_9.horizontalHeader().setVisible(False)
        self.tableWidget_9.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.groupBox_9)
        self.groupBox_10 = QtGui.QGroupBox(self.widget)
        self.groupBox_10.setMinimumSize(QtCore.QSize(630, 128))
        self.groupBox_10.setObjectName("groupBox_10")
        self.tableWidget_10 = QtGui.QTableWidget(self.groupBox_10)
        self.tableWidget_10.setGeometry(QtCore.QRect(10, 30, 611, 92))
        self.tableWidget_10.setShowGrid(True)
        self.tableWidget_10.setObjectName("tableWidget_10")
        self.tableWidget_10.setColumnCount(1)
        self.tableWidget_10.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_10.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_10.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_10.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_10.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_10.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_10.setItem(2, 0, item)
        self.tableWidget_10.horizontalHeader().setVisible(False)
        self.tableWidget_10.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.groupBox_10)
        self.groupBox_11 = QtGui.QGroupBox(self.widget)
        self.groupBox_11.setMinimumSize(QtCore.QSize(630, 99))
        self.groupBox_11.setObjectName("groupBox_11")
        self.tableWidget_11 = QtGui.QTableWidget(self.groupBox_11)
        self.tableWidget_11.setGeometry(QtCore.QRect(10, 30, 611, 62))
        self.tableWidget_11.setShowGrid(True)
        self.tableWidget_11.setObjectName("tableWidget_11")
        self.tableWidget_11.setColumnCount(1)
        self.tableWidget_11.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_11.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_11.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_11.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_11.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_11.setItem(1, 0, item)
        self.tableWidget_11.horizontalHeader().setVisible(False)
        self.tableWidget_11.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.groupBox_11)
        self.groupBox_12 = QtGui.QGroupBox(self.widget)
        self.groupBox_12.setMinimumSize(QtCore.QSize(630, 128))
        self.groupBox_12.setObjectName("groupBox_12")
        self.tableWidget_12 = QtGui.QTableWidget(self.groupBox_12)
        self.tableWidget_12.setGeometry(QtCore.QRect(10, 30, 611, 92))
        self.tableWidget_12.setShowGrid(True)
        self.tableWidget_12.setObjectName("tableWidget_12")
        self.tableWidget_12.setColumnCount(1)
        self.tableWidget_12.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_12.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_12.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_12.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_12.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_12.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_12.setItem(2, 0, item)
        self.tableWidget_12.horizontalHeader().setVisible(False)
        self.tableWidget_12.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.groupBox_12)
        self.verticalLayout.addWidget(self.widget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Dialog_InfoGen)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog_InfoGen.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog_InfoGen.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_InfoGen)
        Dialog_InfoGen.setTabOrder(self.scrollArea, self.tableWidget)
        Dialog_InfoGen.setTabOrder(self.tableWidget, self.tableWidget_2)
        Dialog_InfoGen.setTabOrder(self.tableWidget_2, self.tableWidget_3)
        Dialog_InfoGen.setTabOrder(self.tableWidget_3, self.tableWidget_4)
        Dialog_InfoGen.setTabOrder(self.tableWidget_4, self.tableWidget_5)
        Dialog_InfoGen.setTabOrder(self.tableWidget_5, self.tableWidget_6)
        Dialog_InfoGen.setTabOrder(self.tableWidget_6, self.tableWidget_7)
        Dialog_InfoGen.setTabOrder(self.tableWidget_7, self.tableWidget_8)
        Dialog_InfoGen.setTabOrder(self.tableWidget_8, self.tableWidget_9)
        Dialog_InfoGen.setTabOrder(self.tableWidget_9, self.tableWidget_10)
        Dialog_InfoGen.setTabOrder(self.tableWidget_10, self.tableWidget_11)
        Dialog_InfoGen.setTabOrder(self.tableWidget_11, self.tableWidget_12)
        Dialog_InfoGen.setTabOrder(self.tableWidget_12, self.buttonBox)

    def retranslateUi(self, Dialog_InfoGen):
        Dialog_InfoGen.setWindowTitle(QtGui.QApplication.translate("Dialog_InfoGen", "Información General", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog_InfoGen", "Información Económica", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Ingreso - frecuencia y constancia de trabajo", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Cantidad de dinero para alimentación semana o mes", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog_InfoGen", "¿Recibe ayuda?", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Persona responsable de economía", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Descripción / Aclaraciones", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog_InfoGen", "Actividad física", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Ocupación - tipo, horas/semana, turno", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Ejercicio (tipo, cantidad, frecuencia)", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Sueño (horas/día) ¿Sin interrupción?", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.verticalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Incapacidades", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Descripción / Aclaraciones", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog_InfoGen", "Antecedentes étnicos o culturales", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Influencia en los hábitos alimenticios", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Religión", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Educación", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Descripción / Aclaraciones", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog_InfoGen", "Vida casera y patrones de comidas", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_4.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Número en la casa (¿Comen juntos?)", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_4.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Personas que hacen la compra", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_4.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Personas que cocinan", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_4.verticalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Instalaciones para guardar alimentos y cocinarlos", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_4.verticalHeaderItem(4).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Tipo de alojamiento", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_4.verticalHeaderItem(5).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Capacidad para comprar y preparar alimentos", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_4.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Descripción / Aclaraciones", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_4.isSortingEnabled()
        self.tableWidget_4.setSortingEnabled(False)
        self.tableWidget_4.setSortingEnabled(__sortingEnabled)
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Dialog_InfoGen", "Apetito", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_5.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Malo, bueno, algún cambio", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_5.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Factores que afectan al apetito", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_5.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Percepción del gusto, olfato y cualquier cambio", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_5.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Descripción / Aclaraciones", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_5.isSortingEnabled()
        self.tableWidget_5.setSortingEnabled(False)
        self.tableWidget_5.setSortingEnabled(__sortingEnabled)
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Dialog_InfoGen", "Actitud hacia el alimento y la alimentación", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_6.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Falta de interés en el alimento", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_6.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Ideas irracionales sobre el alimento, comer y peso", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_6.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Descripción / Aclaraciones", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_6.isSortingEnabled()
        self.tableWidget_6.setSortingEnabled(False)
        self.tableWidget_6.setSortingEnabled(__sortingEnabled)
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Dialog_InfoGen", "Alergias, intolerancias o rechazo de alimentos", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_7.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Alimentos que se rechazan y razón", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_7.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Tiempo en que se han rechazado", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_7.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Descripción de problemas causados por alimentos", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_7.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Descripción / Aclaraciones", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_7.isSortingEnabled()
        self.tableWidget_7.setSortingEnabled(False)
        self.tableWidget_7.setSortingEnabled(__sortingEnabled)
        self.groupBox_8.setTitle(QtGui.QApplication.translate("Dialog_InfoGen", "Salud dental y bucal", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_8.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Problemas con la alimentación", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_8.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Alimentos que no puede comer", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_8.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Problemas con la deglución, salivación, viscosidad del alimento", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_8.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Descripción / Aclaraciones", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_8.isSortingEnabled()
        self.tableWidget_8.setSortingEnabled(False)
        self.tableWidget_8.setSortingEnabled(__sortingEnabled)
        self.groupBox_9.setTitle(QtGui.QApplication.translate("Dialog_InfoGen", "Gastrointestinales", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_9.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Problemas por pirosis, timpanismo, gas, ...", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_9.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Frecuencia de problemas", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_9.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Remedios caseros", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_9.verticalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Uso de antiácidos, laxantes u otros fármacos", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_9.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Descripción / Aclaraciones", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_9.isSortingEnabled()
        self.tableWidget_9.setSortingEnabled(False)
        self.tableWidget_9.setSortingEnabled(__sortingEnabled)
        self.groupBox_10.setTitle(QtGui.QApplication.translate("Dialog_InfoGen", "Enfermedad crónica", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_10.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Tratamiento", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_10.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Duración del tratamiento", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_10.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Modificación de la dieta", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_10.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Descripción / Aclaraciones", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_10.isSortingEnabled()
        self.tableWidget_10.setSortingEnabled(False)
        self.tableWidget_10.setSortingEnabled(__sortingEnabled)
        self.groupBox_11.setTitle(QtGui.QApplication.translate("Dialog_InfoGen", "Medicamentos", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_11.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Suplementos de vitaminas o minerales", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_11.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Medicamentos - tipo, cantidad, frecuencia", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_11.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Descripción / Aclaraciones", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_11.isSortingEnabled()
        self.tableWidget_11.setSortingEnabled(False)
        self.tableWidget_11.setSortingEnabled(__sortingEnabled)
        self.groupBox_12.setTitle(QtGui.QApplication.translate("Dialog_InfoGen", "Cambio reciente de peso", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_12.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Pérdida o aumento", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_12.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Cuántos kilos, en qué tiempo", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_12.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Intencional o no voluntario", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_12.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_InfoGen", "Descripción / Aclaraciones", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_12.isSortingEnabled()
        self.tableWidget_12.setSortingEnabled(False)
        self.tableWidget_12.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog_InfoGen = QtGui.QDialog()
    ui = Ui_Dialog_InfoGen()
    ui.setupUi(Dialog_InfoGen)
    Dialog_InfoGen.show()
    sys.exit(app.exec_())

