# -*- coding: utf-8 -*-
import sys
import sqlite3 as dbapi

sys.path.append('PY_UIs')

from PyQt4 import Qt
from abrirperfildiet import *
from perfildietista_pass import *
from cerrarperfil import *
from registrodietista import *
from eliminarperfil import *

class TableWidgetItem(QtGui.QTableWidgetItem):
    def __init__(self, parent = None):
        super(TableWidgetItem, self).__init__()
        self.cal = 0
        
class TableWidget(QtGui.QTableWidget):
    def dropMimeData(self, row, column, data, action):
        #Declaracion y conexion con la bbdd
        bbdd = dbapi.connect('edp11.bd')
        cursor = bbdd.cursor()        
        #Comportamiento del modelo
        model = QtGui.QStandardItemModel()

        model.dropMimeData(data, Qt.Qt.CopyAction, 0, 0, Qt.QModelIndex())
        dropped = model.item(0).text()
        item = self.item(row, column)
        cursor.execute("select r_cal from Receta where r_nombre=?",(unicode(dropped),))
        res = cursor.fetchone()

        if item.text() == "":
            item.setText("%s" % dropped)
            item.cal = res[0]
        else:
            item.setText("%s, %s" % (item.text(), dropped))
            item.cal += res[0]
 
        #Cierre de la bbdd y de la consulta
        cursor.close()
        bbdd.close()
        return True

class Dietista:
    def __init__(self, GUI):
        self.perfil = ""
        self.gui = GUI

    def ObtenerPerfil(self):
        return self.perfil

    def ObtenerGui(self):
        return self.gui
    
    def SetPerfil(self, id):
        self.perfil = id

    def VentanaAbrir(self):
        #Declaraciones de la accion Abrir Perfil Dietista
        self.WindowPDiet = QtGui.QDialog()
        self.uiPD = Ui_DialogDiet()
        self.uiPD.setupUi(self.WindowPDiet)

#Conexion de accion Abrir Perfil Dietista y GUI Perfil Dietista
    def MostrarDietistas(self):
        #Declaracion y conexion con la bbdd
        bbdd = dbapi.connect('edp11.bd')
        cursor = bbdd.cursor()        
        #Mostrar registros de la bbdd y mostrar la GUI
        cursor.execute("select d_nombre, d_dni from Dietista")
        items = cursor.fetchall()
        self.uiPD.treeWidget.clear()
        if items:
            for i in range(len(items)):
                item = QtGui.QTreeWidgetItem(self.uiPD.treeWidget,0)
                item.setText(0,items[i][0])
                item.setText(1,items[i][1])
                self.uiPD.treeWidget.addTopLevelItem(item)
        self.uiPD.treeWidget.sortItems(0,0)
        I = self.uiPD.treeWidget.itemAt(0,0)
        self.uiPD.treeWidget.setCurrentItem(I)
        self.WindowPDiet.show()
        #Cierre de la bbdd y de la consulta
        cursor.close()
        bbdd.close()

#Declaracion GUI Perfil Dietista Pass
    def VentanaLogin(self):
        self.WindowPDPass = QtGui.QDialog()
        self.uiPDP = Ui_Dialog_PD_Pass()
        self.uiPDP.setupUi(self.WindowPDPass)  

#Conexion button Aceptar de Perfil Dietista y GUI Perfil Dietista Pass
    def AceptarPass(self):
        item = self.uiPD.treeWidget.currentItem()
        column = self.uiPD.treeWidget.currentColumn()
        perfil = unicode(self.uiPD.treeWidget.currentItem().text(0))
        self.uiPDP.lineEdit_PD.setText(perfil)
        self.uiPDP.label_error.setText("")
        self.uiPDP.lineEdit_Pass.clear()    
        self.WindowPDPass.show()

#Comprobacion de Perfil Dietista y password
    def IniciaTabla(self,ui):
        #Tabla para 6 ingestas
        ui.tableWidget_5 = TableWidget(ui.page_4)
        ui.tableWidget_5.setEnabled(True)
        ui.tableWidget_5.setGeometry(QtCore.QRect(47, 12, 813, 207))
        ui.tableWidget_5.setDragDropOverwriteMode(True)
        ui.tableWidget_5.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        ui.tableWidget_5.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        ui.tableWidget_5.setCornerButtonEnabled(False)
        ui.tableWidget_5.setRowCount(6)
        ui.tableWidget_5.setColumnCount(7)
        ui.tableWidget_5.setObjectName("tableWidget_5")
        item = TableWidgetItem()
        ui.tableWidget_5.setVerticalHeaderItem(0, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setVerticalHeaderItem(1, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setVerticalHeaderItem(2, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setVerticalHeaderItem(3, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setVerticalHeaderItem(4, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setVerticalHeaderItem(5, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setHorizontalHeaderItem(5, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setHorizontalHeaderItem(6, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(0, 0, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(0, 1, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(0, 2, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(0, 3, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(0, 4, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(0, 5, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(0, 6, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(1, 0, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(1, 1, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(1, 2, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(1, 3, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(1, 4, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(1, 5, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(1, 6, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(2, 0, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(2, 1, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(2, 2, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(2, 3, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(2, 4, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(2, 5, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(2, 6, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(3, 0, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(3, 1, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(3, 2, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(3, 3, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(3, 4, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(3, 5, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(3, 6, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(4, 0, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(4, 1, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(4, 2, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(4, 3, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(4, 4, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(4, 5, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(4, 6, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(5, 0, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(5, 1, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(5, 2, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(5, 3, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(5, 4, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(5, 5, item)
        item = TableWidgetItem()
        ui.tableWidget_5.setItem(5, 6, item)
        ui.tableWidget_5.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Desayuno", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_5.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Media Mañana", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_5.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Almuerzo", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_5.verticalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Merienda", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_5.verticalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Cena", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_5.verticalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Tentempié", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_5.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Lunes", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_5.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Martes", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_5.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Miércoles", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_5.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Jueves", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_5.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Viernes", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_5.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Sábado", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_5.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Domingo", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = ui.tableWidget_5.isSortingEnabled()
        ui.tableWidget_5.setSortingEnabled(False)
        ui.tableWidget_5.setSortingEnabled(__sortingEnabled)

        #Tabla para 5 ingestas
        ui.tableWidget_4 = TableWidget(ui.page_3)
        ui.tableWidget_4.setEnabled(True)
        ui.tableWidget_4.setGeometry(QtCore.QRect(47, 12, 813, 177))
        ui.tableWidget_4.setDragDropOverwriteMode(True)
        ui.tableWidget_4.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        ui.tableWidget_4.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        ui.tableWidget_4.setCornerButtonEnabled(False)
        ui.tableWidget_4.setRowCount(5)
        ui.tableWidget_4.setColumnCount(7)
        ui.tableWidget_4.setObjectName("tableWidget_4")
        item = TableWidgetItem()
        ui.tableWidget_4.setVerticalHeaderItem(0, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setVerticalHeaderItem(1, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setVerticalHeaderItem(2, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setVerticalHeaderItem(3, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setVerticalHeaderItem(4, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setHorizontalHeaderItem(5, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setHorizontalHeaderItem(6, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(0, 0, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(0, 1, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(0, 2, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(0, 3, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(0, 4, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(0, 5, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(0, 6, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(1, 0, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(1, 1, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(1, 2, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(1, 3, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(1, 4, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(1, 5, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(1, 6, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(2, 0, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(2, 1, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(2, 2, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(2, 3, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(2, 4, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(2, 5, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(2, 6, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(3, 0, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(3, 1, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(3, 2, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(3, 3, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(3, 4, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(3, 5, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(3, 6, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(4, 0, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(4, 1, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(4, 2, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(4, 3, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(4, 4, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(4, 5, item)
        item = TableWidgetItem()
        ui.tableWidget_4.setItem(4, 6, item)
        ui.tableWidget_4.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Desayuno", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_4.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Media Mañana", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_4.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Almuerzo", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_4.verticalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Merienda", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_4.verticalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Cena", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_4.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Lunes", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_4.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Martes", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_4.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Miércoles", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_4.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Jueves", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_4.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Viernes", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_4.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Sábado", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_4.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Domingo", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = ui.tableWidget_4.isSortingEnabled()
        ui.tableWidget_4.setSortingEnabled(False)
        ui.tableWidget_4.setSortingEnabled(__sortingEnabled)

        #Tabla para 4 ingestas
        ui.tableWidget_3 = TableWidget(ui.page_2)
        ui.tableWidget_3.setEnabled(True)
        ui.tableWidget_3.setGeometry(QtCore.QRect(60, 40, 781, 147))
        ui.tableWidget_3.setDragDropOverwriteMode(True)
        ui.tableWidget_3.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        ui.tableWidget_3.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        ui.tableWidget_3.setCornerButtonEnabled(False)
        ui.tableWidget_3.setRowCount(4)
        ui.tableWidget_3.setColumnCount(7)
        ui.tableWidget_3.setObjectName("tableWidget_3")
        item = TableWidgetItem()
        ui.tableWidget_3.setVerticalHeaderItem(0, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setVerticalHeaderItem(1, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setVerticalHeaderItem(2, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setVerticalHeaderItem(3, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(0, 0, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(0, 1, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(0, 2, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(0, 3, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(0, 4, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(0, 5, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(0, 6, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(1, 0, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(1, 1, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(1, 2, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(1, 3, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(1, 4, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(1, 5, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(1, 6, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(2, 0, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(2, 1, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(2, 2, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(2, 3, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(2, 4, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(2, 5, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(2, 6, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(3, 0, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(3, 1, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(3, 2, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(3, 3, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(3, 4, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(3, 5, item)
        item = TableWidgetItem()
        ui.tableWidget_3.setItem(3, 6, item)
        ui.tableWidget_3.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Desayuno", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_3.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Almuerzo", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_3.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Merienda", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_3.verticalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cena", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_3.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Lunes", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_3.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Martes", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_3.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Miércoles", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_3.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Jueves", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_3.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Viernes", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_3.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Sábado", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_3.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Domingo", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = ui.tableWidget_3.isSortingEnabled()
        ui.tableWidget_3.setSortingEnabled(False)
        ui.tableWidget_3.setSortingEnabled(__sortingEnabled)

        #Tabla para 3 ingestas
        ui.tableWidget_2 = TableWidget(ui.page)
        ui.tableWidget_2.setEnabled(True)
        ui.tableWidget_2.setGeometry(QtCore.QRect(60, 50, 781, 117))
        ui.tableWidget_2.setDragDropOverwriteMode(True)
        ui.tableWidget_2.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        ui.tableWidget_2.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        ui.tableWidget_2.setCornerButtonEnabled(False)
        ui.tableWidget_2.setRowCount(3)
        ui.tableWidget_2.setColumnCount(7)
        ui.tableWidget_2.setObjectName("tableWidget_2")
        item = TableWidgetItem()
        ui.tableWidget_2.setVerticalHeaderItem(0, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setVerticalHeaderItem(1, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setVerticalHeaderItem(2, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(0, 0, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(0, 1, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(0, 2, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(0, 3, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(0, 4, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(0, 5, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(0, 6, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(1, 0, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(1, 1, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(1, 2, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(1, 3, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(1, 4, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(1, 5, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(1, 6, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(2, 0, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(2, 1, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(2, 2, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(2, 3, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(2, 4, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(2, 5, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(2, 6, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(3, 0, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(3, 1, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(3, 2, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(3, 3, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(3, 4, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(3, 5, item)
        item = TableWidgetItem()
        ui.tableWidget_2.setItem(3, 6, item)
        ui.tableWidget_2.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Desayuno", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_2.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Almuerzo", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_2.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Cena", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_2.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Lunes", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_2.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Martes", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_2.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Miércoles", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_2.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Jueves", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_2.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Viernes", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_2.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Sábado", None, QtGui.QApplication.UnicodeUTF8))
        ui.tableWidget_2.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Domingo", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = ui.tableWidget_2.isSortingEnabled()
        ui.tableWidget_2.setSortingEnabled(False)
        ui.tableWidget_2.setSortingEnabled(__sortingEnabled)

        
    def Aceptar(self,ui):
        #Declaracion y conexion con la bbdd
        bbdd = dbapi.connect('edp11.bd')
        cursor = bbdd.cursor()
        #Consultar pass del item del treeWidget y de la bbdd
        item = self.uiPD.treeWidget.currentItem()
        column = self.uiPD.treeWidget.currentColumn()
        D = str(self.uiPD.treeWidget.currentItem().text(1))
        P = unicode(self.uiPD.treeWidget.currentItem().text(0))
        cursor.execute("select d_passwd from Dietista where d_dni=?",(D,))
        if unicode(cursor.fetchone()[0])!= self.uiPDP.lineEdit_Pass.text():
            self.uiPDP.lineEdit_Pass.clear()
            self.uiPDP.label_error.setText(u"La contraseña no es correcta.")
            self.WindowPDPass.show()
        else:
            self.perfil = D
            titulo = u"Estudio Dietético Programado 2011 - " + P
            self.gui.PonerEnabled()
            self.gui.PonerTitulo(titulo)
            self.gui.ui.actionDietista.setEnabled(False)
            self.IniciaTabla(ui)
        #Cierre de la bbdd y de la consulta
        cursor.close()
        bbdd.close()

    def VentanaCerrar(self):
        #Declaraciones de la accion Cerrar Perfil 
        self.WindowCPer = QtGui.QDialog()
        self.uiCPe = Ui_DialogCPerf()
        self.uiCPe.setupUi(self.WindowCPer)

    def CerrarPerf(self):
        self.perfil = ""
        self.gui.QuitarEnabled()
        self.gui.PonerTitulo(u"Estudio Dietético Programado 2011")

    def VentanaRegistro(self):
        #Declaracion Registro Dietista
        self.WindowRD = QtGui.QDialog()
        self.uiRD = Ui_Dialog_RegD()
        self.uiRD.setupUi(self.WindowRD)

    def Nuevo(self):
        self.uiRD.lineEdit_dni.clear()
        self.uiRD.lineEdit_nom.clear()
        self.uiRD.lineEdit_pass.clear()
        self.uiRD.lineEdit_pass2.clear()
        self.uiRD.label_verif.setText("")
        self.uiRD.label_verif2.setText("")
        self.uiRD.label_verif3.setText("")
        self.WindowRD.show()

    def Verificar(self):
        #Declaracion y conexion con la bbdd
        bbdd = dbapi.connect('edp11.bd')
        cursor = bbdd.cursor()

        #Comprobaciones
        salida = True
        salida1 = True
        salida2 = True

        cursor.execute("select d_nombre from Dietista where d_dni=?",(unicode(self.uiRD.lineEdit_dni.text()),))
        existe = cursor.fetchone()
        if existe:
            self.uiRD.lineEdit_dni.clear()
            self.uiRD.label_verif.setText("D.N.I. Existente")
            salida1 = False
            self.WindowRD.show()
        elif len(self.uiRD.lineEdit_dni.text())!= 9:
            self.uiRD.lineEdit_dni.clear()
            self.uiRD.label_verif.setText("D.N.I. Incorrecto")
            salida1 = False
            self.WindowRD.show()
        elif len(self.uiRD.lineEdit_dni.text())== 9:
            nif = 'TRWAGMYFPDXBNJZSQVHLCKE'
            #Si empieza por X (DNIE)
            if self.uiRD.lineEdit_dni.text()[0] == "X":
                dni = int(self.uiRD.lineEdit_dni.text()[1:-1])
            #Si empieza por Y (DNIE)
            elif self.uiRD.lineEdit_dni.text()[0] == "Y":
                dnie = "1" + self.uiRD.lineEdit_dni.text()[1:-1]
                dni = int(dnie)
            #Si empieza por numero (DNI)
            else:
                dni = int(self.uiRD.lineEdit_dni.text()[:-1])
            #Comprobacion de letra
            if nif[dni%23] != self.uiRD.lineEdit_dni.text()[-1:]:
                self.uiRD.lineEdit_dni.clear()
                self.uiRD.label_verif.setText("D.N.I. Incorrecto")
                salida1 = False
                self.WindowRD.show()
            else:
                self.uiRD.label_verif.setText("")
                salida1 = True
        else:
            self.uiRD.label_verif.setText("")
            salida1 = True
        if self.uiRD.lineEdit_pass.text() != self.uiRD.lineEdit_pass2.text():
            self.uiRD.label_verif2.setText(u"Las contraseñas")
            self.uiRD.label_verif3.setText("no coinciden.")
            self.uiRD.lineEdit_pass2.clear()
            salida2 = False
            self.WindowRD.show()
        else:
            self.uiRD.label_verif2.setText("")
            self.uiRD.label_verif3.setText("")
            salida2 = True
        salida = salida1 & salida2
        #Cierre de la bbdd y de la consulta
        cursor.close()
        bbdd.close()

        return salida

    def GuardarDietista(self):
        #Declaracion y conexion con la bbdd
        bbdd = dbapi.connect('edp11.bd')
        cursor = bbdd.cursor()
        #Insertar en treeWidget los datos dni y nombre
        if self.Verificar():
            item = QtGui.QTreeWidgetItem(self.uiPD.treeWidget,0)
            item.setText(0,self.uiRD.lineEdit_nom.text())
            item.setText(1,self.uiRD.lineEdit_dni.text())
            self.uiPD.treeWidget.addTopLevelItem(item)
            self.uiPD.treeWidget.sortItems(0,0)
        #Inserccion en la bbdd
            D = unicode(self.uiRD.lineEdit_dni.text())
            N = unicode(self.uiRD.lineEdit_nom.text())
            P = unicode(self.uiRD.lineEdit_pass.text())
            cursor.execute("insert into Dietista values (?,?,?)",(D,N,P,))
            bbdd.commit()
        #Cierre de la bbdd y de la consulta
        cursor.close()
        bbdd.close()

    def VentanaEliminar(self):
        #Declaracion GUI Eliminar Perfil
        self.WindowEP = QtGui.QDialog()
        self.uiEP = Ui_DialogEPerf()
        self.uiEP.setupUi(self.WindowEP)  

    def Eliminar(self):
        self.uiEP.lineEdit.clear()
        self.uiEP.label_error.setText("")
        self.WindowEP.show()

    def ElimPerf(self):
        if self.uiEP.lineEdit.text() == "30121976":
            #Declaracion y conexion con la bbdd
            bbdd = dbapi.connect('edp11.bd')
            cursor = bbdd.cursor()
            #Eliminacion del item del treeWidget y de la bbdd
            item = self.uiPD.treeWidget.currentItem()
            column = self.uiPD.treeWidget.currentColumn()
            D = str(self.uiPD.treeWidget.currentItem().text(1))
            cursor.execute("delete from Dietista where d_dni=?",(D,))
            bbdd.commit()
            self.uiPD.treeWidget.removeItemWidget(item,column)
            #Cierre de la bbdd y de la consulta
            cursor.close()
            bbdd.close()
        else:
            self.uiEP.label_error.setText(u"Contraseña Incorrecta.")
            self.WindowEP.show()          
