from ez_setup import use_setuptools
use_setuptools()

from distutils.core import setup
import py2exe

setup(name="Estudio-Dietetico-Programado-2011",
      version="0.1",
      description="Estudio Dietetico Programado. Seguimiento de pacientes y el consumo de una dieta equilibrada",
      author="Manuel Gonzalez",
      author_email="gonzalezperezmanuel@gmail",
      license="GPL3",
      scripts=["usr/share/edp11/mainmenu.py","usr/share/edp11/edp11.bd","usr/share/edp11/GUI.py","usr/share/edp11/dietista.py","usr/share/edp11/paciente.py","usr/share/edp11/ingrediente.py","usr/share/edp11/receta.py","usr/share/edp11/Docu/basic.odt","usr/share/edp11/Docu/basicweek.odt","usr/share/edp11/Docu/diario_dietetico.pdf","usr/share/edp11/Docu/recordatorio.pdf","usr/share/edp11/Docu/gpl-3.0.pdf","usr/share/edp11/Docu/manual_usuario.pdf","usr/share/edp11/PY_UIs/abrirpaciente.py","usr/share/edp11/PY_UIs/abrirperfildiet.py","usr/share/edp11/PY_UIs/acercade.py","usr/share/edp11/PY_UIs/agregarenfermedad.py","usr/share/edp11/PY_UIs/anadir_ingred.py","usr/share/edp11/PY_UIs/anadirtratapoyo.py","usr/share/edp11/PY_UIs/cerrarpaciente.py","usr/share/edp11/PY_UIs/cerrarperfil.py","usr/share/edp11/PY_UIs/creditos.py","usr/share/edp11/PY_UIs/cuestionariofrecuencia.py","usr/share/edp11/PY_UIs/diariodietetico.py","usr/share/edp11/PY_UIs/edp11.py","usr/share/edp11/PY_UIs/eliminaringrediente.py","usr/share/edp11/PY_UIs/eliminarpaciente.py","usr/share/edp11/PY_UIs/eliminarperfil.py","usr/share/edp11/PY_UIs/eliminarreceta.py","usr/share/edp11/PY_UIs/enfermedad_ingred.py","usr/share/edp11/PY_UIs/infogen.py","usr/share/edp11/PY_UIs/informacionmedica.py","usr/share/edp11/PY_UIs/modificarreceta.py","usr/share/edp11/PY_UIs/nuevaenfermedad.py","usr/share/edp11/PY_UIs/nuevareceta.py","usr/share/edp11/PY_UIs/nuevoingrediente.py","usr/share/edp11/PY_UIs/nuevopaciente1.py","usr/share/edp11/PY_UIs/nuevopaciente2.py","usr/share/edp11/PY_UIs/perfildietista_pass.py","usr/share/edp11/PY_UIs/registrodietista.py","usr/share/edp11/PY_UIs/seleccionarreceta.py","usr/share/edp11/PY_UIs/tabla_niveles.py","usr/share/edp11/PY_UIs/verrecetas.py"],
      windows=["usr/share/edp11/mainmenu.py","usr/share/edp11/edp11.bd","usr/share/edp11/GUI.py","usr/share/edp11/dietista.py","usr/share/edp11/paciente.py","usr/share/edp11/ingrediente.py","usr/share/edp11/receta.py","usr/share/edp11/Docu/basic.odt","usr/share/edp11/Docu/basicweek.odt","usr/share/edp11/Docu/diario_dietetico.pdf","usr/share/edp11/Docu/recordatorio.pdf","usr/share/edp11/Docu/gpl-3.0.pdf","usr/share/edp11/Docu/manual_usuario.pdf","usr/share/edp11/PY_UIs/abrirpaciente.py","usr/share/edp11/PY_UIs/abrirperfildiet.py","usr/share/edp11/PY_UIs/acercade.py","usr/share/edp11/PY_UIs/agregarenfermedad.py","usr/share/edp11/PY_UIs/anadir_ingred.py","usr/share/edp11/PY_UIs/anadirtratapoyo.py","usr/share/edp11/PY_UIs/cerrarpaciente.py","usr/share/edp11/PY_UIs/cerrarperfil.py","usr/share/edp11/PY_UIs/creditos.py","usr/share/edp11/PY_UIs/cuestionariofrecuencia.py","usr/share/edp11/PY_UIs/diariodietetico.py","usr/share/edp11/PY_UIs/edp11.py","usr/share/edp11/PY_UIs/eliminaringrediente.py","usr/share/edp11/PY_UIs/eliminarpaciente.py","usr/share/edp11/PY_UIs/eliminarperfil.py","usr/share/edp11/PY_UIs/eliminarreceta.py","usr/share/edp11/PY_UIs/enfermedad_ingred.py","usr/share/edp11/PY_UIs/infogen.py","usr/share/edp11/PY_UIs/informacionmedica.py","usr/share/edp11/PY_UIs/modificarreceta.py","usr/share/edp11/PY_UIs/nuevaenfermedad.py","usr/share/edp11/PY_UIs/nuevareceta.py","usr/share/edp11/PY_UIs/nuevoingrediente.py","usr/share/edp11/PY_UIs/nuevopaciente1.py","usr/share/edp11/PY_UIs/nuevopaciente2.py","usr/share/edp11/PY_UIs/perfildietista_pass.py","usr/share/edp11/PY_UIs/registrodietista.py","usr/share/edp11/PY_UIs/seleccionarreceta.py","usr/share/edp11/PY_UIs/tabla_niveles.py","usr/share/edp11/PY_UIs/verrecetas.py"],
      options={"py2exe": {"bundle_files": 1}},
      zipfile=None
      )
